<a href="https://colab.research.google.com/github/nilu-ai/Restaurant_Fttx_project/blob/main/Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install deepface

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.3/97.3 kB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 14.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.4/88.4 kB 8.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 7.8 MB/s eta 0:00:00
  Created wheel for fire: filename=fire-0.6.0-py2.py3-none-any.whl size=117029 sha256=8ffbda7d6df78005ef7dc1ef6744eeaa1b43efbba5c474f4ae13669878d4d831
  Stored in directory: /root/.cache/pip/wheels/d6/6d/5d/5b73fa0f46d01a793713f8859201361e9e581ced8c75e5c6a3
Successfully built fire


In [ ]:
!unzip trainss

Archive:  trainss.zip
   creating: trainss/abhi/
  inflating: trainss/abhi/WIN_20240524_15_28_37_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_39_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_41_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_42_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_44_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_45_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_47_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_48_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_50_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_52_Pro.jpg  
   creating: trainss/Abhishek 1/
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_24_Pro (2).jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_24_Pro.jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_25_Pro (2).jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_25_Pro.jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_29_22_Pro.jpg  
  inflatin

In [ ]:
from deepface import DeepFace
df = DeepFace.find(img_path = "/content/trainss/Abhishek 1/WIN_20240524_15_29_24_Pro.jpg", db_path = "/content/trainss",model_name="Facenet512")
print(df)
if df[0].distance.empty:
  print("Unkonw")
elif df[0].distance[0]<0.3:
  print(df)
else:
  print("Unknow User")



24-05-31 11:38:26 - Searching /content/trainss/Abhishek 1/WIN_20240524_15_29_24_Pro.jpg in 36 length datastore
24-05-31 11:38:28 - find function duration 1.9199469089508057 seconds
[                                             identity  \
0   /content/trainss/Abhishek 1/WIN_20240524_15_29...   
1   /content/trainss/Abhishek 1/WIN_20240524_15_28...   
2   /content/trainss/Abhishek 1/WIN_20240524_15_28...   
3   /content/trainss/Abhishek 1/WIN_20240524_15_29...   
4   /content/trainss/Abhishek 1/WIN_20240524_15_29...   
5   /content/trainss/Abhishek 1/WIN_20240524_15_29...   
6   /content/trainss/Abhishek 1/WIN_20240524_15_29...   
7   /content/trainss/Abhishek 1/WIN_20240524_15_28...   
8   /content/trainss/Abhishek 1/WIN_20240524_15_29...   
9   /content/trainss/Abhishek 1/WIN_20240524_15_29...   
10  /content/trainss/Abhishek 1/WIN_20240524_15_29...   
11  /content/trainss/Abhishek 1/WIN_20240524_15_29...   

                                        hash  target_x  target_y  target_w  

In [ ]:
from flask import Flask, request, jsonify
import cv2
import numpy as np
import base64
from deepface import DeepFace
import os
app = Flask(__name__)
from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(5000)"))
@app.route('/', methods=['GET', 'POST'])
def upload_image():
    if request.method == 'POST':
        data = request.json
        img_data = data['image'].split(',')[1]
        nparr = np.frombuffer(base64.b64decode(img_data), np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

        try:

            predictions = DeepFace.find(img_path=img, db_path="/content/trainss", model_name="Facenet512")

            if not predictions[0].empty and predictions[0].distance[0] < 0.3:
                response = {
                    'status': 'success',
                    'data': predictions[0].to_dict()
                }
            else:
                response = {
                    'status': 'unknown User'
                }
        except Exception as e:
            response = {
                'status': 'error',
                'message': str(e)
            }

        return jsonify(response)

    return """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <video id="video" width="640" height="480" autoplay></video>
        <canvas id="canvas" width="640" height="480" style="display:none;"></canvas>
        <div id="prediction"></div>
        <script>
            const video = document.getElementById('video');
            const canvas = document.getElementById('canvas');
            const predictionDiv = document.getElementById('prediction');

            async function initCamera() {
                try {
                    const stream = await navigator.mediaDevices.getUserMedia({ video: true });
                    video.srcObject = stream;
                } catch (err) {
                    console.error('Error accessing camera:', err);
                }
            }

            async function captureAndPredict() {
                const context = canvas.getContext('2d');
                context.drawImage(video, 0, 0, canvas.width, canvas.height);
                const imageData = canvas.toDataURL('image/jpeg');
                const response = await fetch('/', {
                    method: 'POST',
                    body: JSON.stringify({ image: imageData }),
                    headers: {
                        'Content-Type': 'application/json'
                    }
                });
                const result = await response.json();
                predictionDiv.innerHTML = JSON.stringify(result, null, 2);
            }

            setInterval(captureAndPredict, 1000);

            initCamera();
        </script>
    </body>
    </html>
    """


@app.route('/new_user', methods=['GET', 'POST'])
def newuser():
    if request.method == 'POST':
        data = request.get_json()
        username = data['username']
        photos = data['photos']

        # Create directory for the new user
        user_dir = os.path.join('trainss', username)
        os.makedirs(user_dir, exist_ok=True)

        # Save photos
        for i, photo in enumerate(photos):
            photo_data = base64.b64decode(photo.split(',')[1])
            with open(os.path.join(user_dir, f'photo_{i+1}.jpg'), 'wb') as f:
                f.write(photo_data)

        return jsonify({'status': 'success', 'message': 'User data saved.'})

    else:
        return '''
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
            </head>
            <body>
                <video id="video" width="640" height="480" autoplay></video>
                <canvas id="canvas" width="640" height="480" style="display:none;"></canvas>
                    <label>Name: <input id="username" type="text"/></label>
                <button id="submitimage">Submit New Data</button>
                <script>
                    const video = document.getElementById('video');
                    const canvas = document.getElementById('canvas');
                    const submit = document.getElementById('submitimage');
                    const usernameInput = document.getElementById('username');
                    let photos = [];
                    let photoCount = 0;

                    async function initCamera() {
                        try {
                            const stream = await navigator.mediaDevices.getUserMedia({ video: true });
                            video.srcObject = stream;
                        } catch (err) {
                            console.error('Error accessing camera:', err);
                        }
                    }

                    function capturePhoto() {
                        const context = canvas.getContext('2d');
                        context.drawImage(video, 0, 0, canvas.width, canvas.height);
                        const imageData = canvas.toDataURL('image/jpeg');
                        photos.push(imageData);
                    }

                    async function submitData() {
                        if (photoCount < 3) {
                            capturePhoto();
                            photoCount++;
                            setTimeout(submitData, 1000); // Capture a photo every second
                        } else {
                            const username = usernameInput.value;
                            const response = await fetch('/new_user', {
                                method: 'POST',
                                body: JSON.stringify({ username, photos }),
                                headers: {
                                    'Content-Type': 'application/json'
                                }
                            });
                            const result = await response.json();
                            console.log(result);
                        }
                    }

                    submit.addEventListener('click', () => {
                        photoCount = 0;
                        photos = [];
                        submitData();
                    });

                    initCamera();
                </script>
            </body>
            </html>
        '''



if __name__ == '__main__':
    app.run(host='0.0.0.0')


https://svbiubpeh6b-496ff2e9c6d22116-5000-colab.googleusercontent.com/
 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.28.0.12:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:16:10] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:16:12] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:16:13] "POST / HTTP/1.1" 200 -


24-05-31 12:16:13 - Searching [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]] in 36 length datastore
24-05-31 12:16:14 - Searching [[[126 145 148]
  [127 146 149]
  [127 148 150]
  ...
  [157 171 170]
  [156 170 169]
  [157 171 170]]

 [[126 145 148]
  [127 146 149]
  [127 148 150]
  ...
  [158 172 171]
  [158 172 171]
  [160 174 173]]

 [[127 146 149]
  [127 146 149]
  [127 148 150]
  ...
  [160 172 172]
  [161 173 173]
  [162 174 174]]

 ...

 [[159 146 120]
  [161 150 123]
  [177 166 139]
  ...
  [178 202 202]
  [173 197 197]
  [168 192 192]]

 [[157 146 118]
  [165 156 129]
  [180 170 146]
  ...
  [182 206 206]
  [176 200 

INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:16:14] "GET /new_user HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:16:15] "GET /favicon.ico HTTP/1.1" 404 -


24-05-31 12:16:15 - Searching [[[125 150 154]
  [124 149 153]
  [127 149 154]
  ...
  [161 174 176]
  [162 174 174]
  [163 175 175]]

 [[127 152 156]
  [126 151 155]
  [128 150 155]
  ...
  [161 174 176]
  [163 175 175]
  [163 175 175]]

 [[128 150 155]
  [128 150 155]
  [128 150 155]
  ...
  [161 174 176]
  [163 175 175]
  [164 176 176]]

 ...

 [[160 148 130]
  [165 153 135]
  [179 167 149]
  ...
  [182 204 209]
  [176 198 203]
  [174 196 201]]

 [[153 143 126]
  [163 153 136]
  [178 170 153]
  ...
  [187 209 214]
  [176 198 203]
  [178 200 205]]

 [[152 143 129]
  [166 157 143]
  [185 178 161]
  ...
  [194 216 221]
  [177 199 204]
  [178 200 205]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:16:15] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:16:15] "POST / HTTP/1.1" 200 -


24-05-31 12:16:15 - find function duration 1.4636213779449463 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:17:33] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:17:34] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:17:36] "POST / HTTP/1.1" 200 -


24-05-31 12:17:36 - Searching [[[124 134 134]
  [125 135 135]
  [126 136 136]
  ...
  [160 165 163]
  [160 165 163]
  [159 164 162]]

 [[126 136 136]
  [126 136 136]
  [125 135 135]
  ...
  [160 165 163]
  [161 166 164]
  [160 165 163]]

 [[129 139 139]
  [128 138 138]
  [126 136 136]
  ...
  [160 165 163]
  [160 165 163]
  [160 165 163]]

 ...

 [[153 131  96]
  [174 152 116]
  [189 168 130]
  ...
  [186 197 194]
  [183 194 191]
  [167 178 175]]

 [[144 123  92]
  [172 153 120]
  [192 173 138]
  ...
  [190 201 199]
  [185 196 193]
  [171 182 179]]

 [[146 125  97]
  [174 154 123]
  [190 173 140]
  ...
  [188 199 197]
  [186 197 194]
  [176 187 184]]] in 36 length datastore
24-05-31 12:17:37 - Searching [[[135 147 141]
  [134 146 140]
  [133 146 138]
  ...
  [167 168 166]
  [170 171 169]
  [171 172 170]]

 [[134 146 140]
  [133 145 139]
  [132 144 138]
  ...
  [169 170 168]
  [170 171 169]
  [171 172 170]]

 [[134 145 142]
  [133 145 139]
  [132 144 138]
  ...
  [167 170 168]
  [169 17

INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:17:37] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:17:37] "POST / HTTP/1.1" 200 -


24-05-31 12:17:37 - Searching [[[134 144 138]
  [134 144 138]
  [135 145 139]
  ...
  [160 171 169]
  [162 173 171]
  [164 175 173]]

 [[137 147 141]
  [137 147 141]
  [136 146 140]
  ...
  [159 170 168]
  [160 171 169]
  [163 174 172]]

 [[139 148 145]
  [139 148 145]
  [138 147 144]
  ...
  [159 170 168]
  [160 171 169]
  [162 173 171]]

 ...

 [[162 139 107]
  [174 153 121]
  [188 165 133]
  ...
  [185 197 191]
  [185 197 191]
  [176 188 182]]

 [[161 140 108]
  [176 157 124]
  [192 171 140]
  ...
  [188 200 194]
  [187 199 193]
  [180 192 186]]

 [[162 143 110]
  [178 159 126]
  [193 173 142]
  ...
  [190 202 196]
  [188 200 194]
  [184 196 190]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:17:39] "POST / HTTP/1.1" 200 -


24-05-31 12:17:39 - Searching [[[143 148 151]
  [142 147 150]
  [142 147 150]
  ...
  [173 178 177]
  [176 178 178]
  [176 178 178]]

 [[143 148 151]
  [142 147 150]
  [142 147 150]
  ...
  [173 178 177]
  [175 177 177]
  [175 177 177]]

 [[143 148 151]
  [143 148 151]
  [143 148 151]
  ...
  [173 178 177]
  [175 177 177]
  [175 177 177]]

 ...

 [[171 147 123]
  [190 168 143]
  [198 176 151]
  ...
  [193 204 202]
  [188 198 198]
  [179 189 189]]

 [[161 138 116]
  [190 169 147]
  [203 182 160]
  ...
  [196 207 205]
  [192 202 202]
  [186 196 196]]

 [[162 141 120]
  [192 171 150]
  [201 182 161]
  ...
  [200 211 209]
  [195 205 205]
  [189 199 199]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:17:40] "POST / HTTP/1.1" 200 -


24-05-31 12:17:39 - Searching [[[145 150 151]
  [145 150 151]
  [145 150 151]
  ...
  [175 174 178]
  [176 175 177]
  [177 176 178]]

 [[145 150 151]
  [145 150 151]
  [145 150 151]
  ...
  [176 175 179]
  [176 175 177]
  [176 175 177]]

 [[145 150 151]
  [145 150 151]
  [145 150 151]
  ...
  [174 175 179]
  [176 175 177]
  [175 174 176]]

 ...

 [[170 144 114]
  [181 157 127]
  [191 170 139]
  ...
  [194 202 201]
  [189 198 195]
  [187 196 193]]

 [[167 138 111]
  [184 157 130]
  [201 177 149]
  ...
  [202 210 209]
  [196 203 200]
  [194 201 198]]

 [[169 140 113]
  [187 160 133]
  [203 178 152]
  ...
  [202 210 209]
  [195 202 199]
  [195 202 199]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:17:40] "POST / HTTP/1.1" 200 -


24-05-31 12:17:40 - Searching [[[142 154 148]
  [142 154 148]
  [144 155 147]
  ...
  [174 176 176]
  [174 177 175]
  [175 178 176]]

 [[141 153 147]
  [141 153 147]
  [143 153 147]
  ...
  [174 176 176]
  [174 177 175]
  [175 178 176]]

 [[144 153 150]
  [144 154 148]
  [144 154 148]
  ...
  [174 176 176]
  [174 177 175]
  [175 178 176]]

 ...

 [[170 145 129]
  [182 157 141]
  [196 172 154]
  ...
  [187 199 199]
  [187 200 198]
  [181 194 192]]

 [[172 147 137]
  [184 162 150]
  [196 175 160]
  ...
  [194 206 206]
  [190 202 202]
  [181 193 193]]

 [[167 144 136]
  [182 160 149]
  [193 173 162]
  ...
  [198 210 210]
  [194 206 206]
  [184 196 196]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:17:41] "POST / HTTP/1.1" 200 -


24-05-31 12:17:41 - Searching [[[147 155 162]
  [148 156 163]
  [149 157 164]
  ...
  [180 181 179]
  [180 181 179]
  [180 181 179]]

 [[147 155 162]
  [148 156 163]
  [148 156 163]
  ...
  [181 182 180]
  [181 182 180]
  [181 182 180]]

 [[147 156 160]
  [148 157 161]
  [148 157 161]
  ...
  [181 182 180]
  [181 182 180]
  [181 182 180]]

 ...

 [[176 155 128]
  [191 170 143]
  [204 183 156]
  ...
  [201 211 211]
  [194 206 206]
  [182 194 194]]

 [[168 148 123]
  [186 169 143]
  [202 185 159]
  ...
  [207 217 217]
  [201 213 213]
  [191 203 203]]

 [[178 160 137]
  [193 175 152]
  [203 187 164]
  ...
  [205 215 215]
  [200 212 212]
  [192 204 204]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:18:45] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:18:45] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:18:48] "POST / HTTP/1.1" 200 -


24-05-31 12:18:47 - Searching [[[110 116 121]
  [113 119 124]
  [114 121 124]
  ...
  [138 146 146]
  [138 146 146]
  [140 148 148]]

 [[109 115 120]
  [111 117 122]
  [112 119 122]
  ...
  [138 146 146]
  [138 146 146]
  [140 148 148]]

 [[109 115 120]
  [109 115 120]
  [109 116 119]
  ...
  [137 145 145]
  [138 146 146]
  [140 148 148]]

 ...

 [[124 105  78]
  [149 130 103]
  [159 140 113]
  ...
  [158 172 166]
  [153 167 161]
  [150 164 158]]

 [[125 107  84]
  [155 139 116]
  [169 154 128]
  ...
  [164 178 172]
  [158 172 166]
  [156 170 164]]

 [[129 112  91]
  [157 140 119]
  [165 151 128]
  ...
  [169 183 177]
  [161 175 169]
  [155 169 163]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:18:48] "POST / HTTP/1.1" 200 -


24-05-31 12:18:48 - Searching [[[113 123 123]
  [112 122 122]
  [110 120 120]
  ...
  [137 147 147]
  [135 147 147]
  [135 147 147]]

 [[111 121 121]
  [111 121 121]
  [110 120 120]
  ...
  [137 147 147]
  [136 148 148]
  [136 148 148]]

 [[109 119 119]
  [109 119 119]
  [110 120 120]
  ...
  [137 147 147]
  [138 148 148]
  [139 149 149]]

 ...

 [[127 109  86]
  [145 128 102]
  [155 138 112]
  ...
  [154 174 169]
  [153 173 168]
  [141 161 156]]

 [[115  98  77]
  [146 132 110]
  [164 150 128]
  ...
  [163 180 176]
  [153 173 168]
  [143 163 158]]

 [[115 100  81]
  [154 139 120]
  [168 155 133]
  ...
  [169 186 182]
  [157 177 172]
  [150 170 165]]] in 36 length datastore
24-05-31 12:18:49 - Searching [[[142 146 147]
  [140 144 145]
  [138 141 145]
  ...
  [160 173 171]
  [162 173 171]
  [163 174 172]]

 [[142 146 147]
  [141 145 146]
  [140 143 147]
  ...
  [160 173 171]
  [163 174 172]
  [163 174 172]]

 [[140 144 145]
  [141 145 146]
  [141 144 148]
  ...
  [162 173 171]
  [163 17

INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:18:50] "POST / HTTP/1.1" 200 -


24-05-31 12:18:50 - find function duration 0.5690920352935791 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:09] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:10] "GET /favicon.ico HTTP/1.1" 404 -


24-05-31 12:20:11 - Searching [[[117 131 127]
  [115 129 125]
  [117 128 126]
  ...
  [151 154 158]
  [153 154 158]
  [154 155 159]]

 [[117 131 127]
  [114 128 124]
  [116 127 125]
  ...
  [151 154 158]
  [154 155 159]
  [155 156 160]]

 [[119 130 128]
  [117 128 126]
  [116 127 125]
  ...
  [152 156 157]
  [153 156 160]
  [153 156 160]]

 ...

 [[138 148 142]
  [138 148 142]
  [138 148 142]
  ...
  [161 173 167]
  [160 174 168]
  [159 173 167]]

 [[138 149 141]
  [137 148 140]
  [137 148 140]
  ...
  [162 173 170]
  [161 175 169]
  [157 173 166]]

 [[138 149 141]
  [136 147 139]
  [136 147 139]
  ...
  [162 176 172]
  [161 175 169]
  [156 172 165]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:12] "POST / HTTP/1.1" 200 -


24-05-31 12:20:12 - find function duration 0.9797818660736084 seconds
24-05-31 12:20:12 - Searching [[[112 120 127]
  [111 119 126]
  [110 117 126]
  ...
  [138 144 149]
  [136 142 147]
  [137 143 148]]

 [[110 118 125]
  [110 118 125]
  [109 116 125]
  ...
  [138 144 149]
  [137 143 148]
  [138 144 149]]

 [[110 118 125]
  [110 118 125]
  [109 117 124]
  ...
  [138 145 148]
  [138 144 149]
  [140 146 151]]

 ...

 [[130 138 128]
  [130 138 128]
  [129 136 129]
  ...
  [157 164 161]
  [164 169 167]
  [154 160 155]]

 [[131 138 131]
  [130 137 130]
  [128 135 128]
  ...
  [154 161 158]
  [163 169 164]
  [152 159 152]]

 [[131 138 131]
  [129 136 129]
  [127 134 127]
  ...
  [152 159 154]
  [163 169 164]
  [153 160 153]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:13] "POST / HTTP/1.1" 200 -


24-05-31 12:20:13 - find function duration 0.5792291164398193 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:13] "POST / HTTP/1.1" 200 -


24-05-31 12:20:13 - Searching [[[117 126 129]
  [116 125 128]
  [116 125 128]
  ...
  [143 154 152]
  [143 154 152]
  [144 155 153]]

 [[118 127 130]
  [117 126 129]
  [116 125 128]
  ...
  [142 153 151]
  [141 152 150]
  [142 153 151]]

 [[116 125 128]
  [116 125 128]
  [115 124 127]
  ...
  [142 152 152]
  [142 152 152]
  [143 153 153]]

 ...

 [[136 150 139]
  [130 144 133]
  [134 145 137]
  ...
  [152 166 154]
  [166 178 166]
  [166 176 163]]

 [[135 149 138]
  [130 144 133]
  [134 145 137]
  ...
  [146 160 148]
  [165 178 164]
  [173 186 170]]

 [[133 147 136]
  [130 144 133]
  [135 146 138]
  ...
  [146 161 147]
  [160 173 159]
  [166 179 163]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:15] "POST / HTTP/1.1" 200 -


24-05-31 12:20:15 - Searching [[[126 135 138]
  [124 133 136]
  [124 134 134]
  ...
  [152 163 161]
  [152 163 161]
  [152 163 161]]

 [[122 131 134]
  [122 131 134]
  [122 132 132]
  ...
  [151 162 160]
  [152 163 161]
  [153 164 162]]

 [[127 136 139]
  [126 135 138]
  [126 136 136]
  ...
  [153 161 161]
  [153 161 160]
  [156 164 163]]

 ...

 [[150 163 155]
  [148 161 153]
  [141 153 147]
  ...
  [176 185 175]
  [184 192 182]
  [172 180 169]]

 [[141 155 144]
  [142 155 147]
  [140 152 146]
  ...
  [171 180 170]
  [177 183 172]
  [183 190 177]]

 [[142 156 145]
  [142 156 145]
  [139 151 145]
  ...
  [175 183 172]
  [171 177 166]
  [183 187 175]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:15] "POST / HTTP/1.1" 200 -


24-05-31 12:20:15 - Searching [[[124 141 138]
  [124 141 138]
  [124 141 138]
  ...
  [158 166 165]
  [159 167 166]
  [161 169 168]]

 [[126 143 140]
  [125 142 139]
  [124 141 138]
  ...
  [158 166 165]
  [159 167 166]
  [161 169 168]]

 [[128 144 143]
  [126 142 141]
  [124 140 139]
  ...
  [159 167 166]
  [159 167 166]
  [160 168 167]]

 ...

 [[150 161 151]
  [148 159 149]
  [145 156 146]
  ...
  [176 185 175]
  [184 192 182]
  [178 186 175]]

 [[151 160 150]
  [149 158 148]
  [147 156 146]
  ...
  [174 182 171]
  [183 189 178]
  [181 188 175]]

 [[152 161 151]
  [151 160 150]
  [149 158 148]
  ...
  [178 186 175]
  [185 192 179]
  [184 191 178]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:16] "POST / HTTP/1.1" 200 -


24-05-31 12:20:16 - Searching [[[134 141 144]
  [135 142 145]
  [135 142 145]
  ...
  [159 167 167]
  [158 168 168]
  [160 170 170]]

 [[135 142 145]
  [134 141 144]
  [133 140 143]
  ...
  [158 166 166]
  [157 167 167]
  [159 169 169]]

 [[135 142 145]
  [134 141 144]
  [133 140 143]
  ...
  [160 167 170]
  [158 167 170]
  [160 169 172]]

 ...

 [[147 160 152]
  [149 162 154]
  [153 164 154]
  ...
  [178 193 185]
  [160 176 165]
  [166 182 171]]

 [[145 158 150]
  [152 165 157]
  [151 165 154]
  ...
  [181 196 188]
  [163 179 168]
  [169 185 174]]

 [[144 157 149]
  [151 164 156]
  [148 162 151]
  ...
  [181 196 188]
  [166 182 171]
  [174 190 179]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:17] "POST / HTTP/1.1" 200 -


24-05-31 12:20:17 - Searching [[[134 142 142]
  [133 141 141]
  [135 140 141]
  ...
  [154 160 167]
  [153 159 164]
  [154 160 165]]

 [[133 141 141]
  [133 141 141]
  [135 140 141]
  ...
  [152 158 165]
  [153 159 164]
  [154 160 165]]

 [[132 142 142]
  [131 141 141]
  [133 141 141]
  ...
  [150 159 163]
  [150 159 163]
  [151 160 164]]

 ...

 [[176 185 182]
  [175 184 181]
  [173 182 179]
  ...
  [142 160 171]
  [137 154 167]
  [140 157 170]]

 [[177 183 182]
  [176 182 181]
  [172 181 178]
  ...
  [130 147 160]
  [118 134 150]
  [114 133 148]]

 [[177 183 182]
  [176 182 181]
  [172 181 178]
  ...
  [125 142 155]
  [104 122 139]
  [ 98 116 133]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:18] "POST / HTTP/1.1" 200 -


24-05-31 12:20:18 - Searching [[[139 146 149]
  [137 144 147]
  [136 143 146]
  ...
  [151 165 164]
  [151 165 164]
  [151 165 164]]

 [[138 145 148]
  [137 144 147]
  [136 143 146]
  ...
  [152 166 165]
  [151 165 164]
  [151 165 164]]

 [[138 145 148]
  [137 144 147]
  [136 143 146]
  ...
  [152 166 165]
  [152 166 165]
  [151 165 164]]

 ...

 [[175 181 164]
  [172 178 161]
  [168 175 160]
  ...
  [139 144 135]
  [159 163 152]
  [174 178 167]]

 [[174 179 164]
  [172 177 162]
  [168 175 160]
  ...
  [147 152 143]
  [163 167 156]
  [175 179 168]]

 [[173 178 163]
  [171 176 161]
  [168 175 160]
  ...
  [153 161 151]
  [165 169 158]
  [171 175 164]]] in 36 length datastore
24-05-31 12:20:19 - Searching [[[141 152 149]
  [141 152 149]
  [138 152 148]
  ...
  [154 165 169]
  [155 167 169]
  [156 168 170]]

 [[139 150 147]
  [139 150 147]
  [137 151 147]
  ...
  [154 165 169]
  [154 166 168]
  [154 166 168]]

 [[140 151 149]
  [140 151 149]
  [138 151 149]
  ...
  [156 167 171]
  [155 16

INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:20] "POST / HTTP/1.1" 200 -


24-05-31 12:20:20 - find function duration 0.6695654392242432 seconds
24-05-31 12:20:20 - Searching [[[139 141 151]
  [139 141 151]
  [140 143 151]
  ...
  [157 168 172]
  [156 165 169]
  [154 163 167]]

 [[140 142 152]
  [140 142 152]
  [140 143 151]
  ...
  [157 168 172]
  [158 167 171]
  [157 166 170]]

 [[142 145 153]
  [142 145 153]
  [141 144 152]
  ...
  [156 167 171]
  [158 167 171]
  [159 168 172]]

 ...

 [[182 187 172]
  [179 184 169]
  [172 179 166]
  ...
  [143 151 144]
  [153 160 153]
  [165 172 165]]

 [[181 186 171]
  [178 183 168]
  [174 178 166]
  ...
  [156 164 157]
  [160 167 160]
  [167 174 167]]

 [[179 184 169]
  [177 182 167]
  [175 179 167]
  ...
  [169 177 170]
  [171 178 171]
  [175 182 175]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:21] "POST / HTTP/1.1" 200 -


24-05-31 12:20:21 - find function duration 0.6425139904022217 seconds
24-05-31 12:20:21 - Searching [[[144 153 156]
  [142 151 154]
  [142 151 155]
  ...
  [164 172 172]
  [167 173 172]
  [168 174 173]]

 [[143 152 155]
  [142 151 154]
  [142 151 155]
  ...
  [164 172 172]
  [167 172 173]
  [167 173 172]]

 [[142 151 154]
  [142 151 154]
  [142 151 155]
  ...
  [165 173 173]
  [167 172 173]
  [167 172 173]]

 ...

 [[184 188 177]
  [180 184 173]
  [178 184 173]
  ...
  [163 167 162]
  [162 163 159]
  [171 172 168]]

 [[187 191 180]
  [181 185 174]
  [177 183 172]
  ...
  [173 179 174]
  [172 176 171]
  [177 181 176]]

 [[189 193 182]
  [180 184 173]
  [175 181 170]
  ...
  [180 186 181]
  [178 182 177]
  [181 185 180]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:22] "POST / HTTP/1.1" 200 -


24-05-31 12:20:22 - find function duration 0.6281330585479736 seconds
24-05-31 12:20:22 - Searching [[[155 164 168]
  [154 163 167]
  [153 162 166]
  ...
  [175 182 185]
  [175 183 183]
  [175 183 183]]

 [[154 163 167]
  [154 163 167]
  [152 161 165]
  ...
  [174 181 184]
  [174 182 182]
  [175 183 183]]

 [[153 162 165]
  [153 162 165]
  [152 161 165]
  ...
  [173 180 183]
  [173 181 181]
  [174 182 182]]

 ...

 [[191 196 181]
  [189 196 181]
  [187 193 182]
  ...
  [173 180 175]
  [171 178 173]
  [182 189 184]]

 [[190 197 182]
  [190 197 182]
  [189 195 184]
  ...
  [179 188 185]
  [180 187 184]
  [186 193 190]]

 [[190 197 182]
  [191 198 183]
  [188 196 185]
  ...
  [183 192 189]
  [186 193 190]
  [190 197 194]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:23] "POST / HTTP/1.1" 200 -


24-05-31 12:20:23 - Searching [[[152 163 160]
  [151 162 159]
  [149 163 159]
  ...
  [171 181 188]
  [170 181 189]
  [169 180 188]]

 [[151 162 159]
  [151 162 159]
  [151 162 159]
  ...
  [171 181 188]
  [170 181 189]
  [170 181 189]]

 [[155 163 162]
  [152 163 161]
  [152 163 161]
  ...
  [170 180 187]
  [170 181 189]
  [171 182 190]]

 ...

 [[195 198 182]
  [192 197 182]
  [191 195 183]
  ...
  [167 176 166]
  [155 163 156]
  [173 181 174]]

 [[193 198 183]
  [193 198 183]
  [191 195 183]
  ...
  [191 200 190]
  [185 193 186]
  [184 192 185]]

 [[192 197 182]
  [191 196 181]
  [189 196 183]
  ...
  [190 199 189]
  [188 196 189]
  [186 194 187]]] in 36 length datastore
24-05-31 12:20:23 - find function duration 0.9121694564819336 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:23] "POST / HTTP/1.1" 200 -


24-05-31 12:20:24 - Searching [[[161 160 170]
  [162 161 171]
  [162 161 170]
  ...
  [173 182 185]
  [173 182 185]
  [173 182 185]]

 [[161 160 170]
  [161 160 169]
  [161 160 169]
  ...
  [173 182 185]
  [173 182 185]
  [173 182 185]]

 [[161 160 169]
  [161 160 169]
  [158 160 168]
  ...
  [173 182 185]
  [173 182 185]
  [173 182 185]]

 ...

 [[194 196 184]
  [192 196 184]
  [191 195 184]
  ...
  [166 175 165]
  [165 173 163]
  [178 186 175]]

 [[192 196 185]
  [192 196 185]
  [191 194 185]
  ...
  [183 192 182]
  [182 191 181]
  [190 200 188]]

 [[192 196 185]
  [192 196 185]
  [190 195 186]
  ...
  [197 206 196]
  [186 195 185]
  [186 196 184]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:24] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:25] "POST / HTTP/1.1" 200 -


24-05-31 12:20:25 - Searching [[[153 170 173]
  [153 170 173]
  [153 171 172]
  ...
  [186 190 195]
  [186 191 194]
  [186 191 194]]

 [[154 171 174]
  [153 170 173]
  [152 170 171]
  ...
  [186 190 195]
  [186 191 194]
  [186 191 194]]

 [[156 171 174]
  [155 170 173]
  [154 169 171]
  ...
  [185 189 194]
  [185 190 193]
  [187 192 195]]

 ...

 [[199 202 193]
  [199 202 193]
  [197 201 190]
  ...
  [141 162 160]
  [110 131 129]
  [139 160 158]]

 [[197 202 193]
  [196 201 192]
  [195 201 190]
  ...
  [107 128 125]
  [ 91 112 109]
  [131 154 150]]

 [[199 204 195]
  [198 203 194]
  [196 202 191]
  ...
  [ 97 118 115]
  [ 87 110 106]
  [129 152 148]]] in 36 length datastore
24-05-31 12:20:26 - Searching [[[164 172 172]
  [163 171 171]
  [160 170 170]
  ...
  [185 191 190]
  [184 192 191]
  [184 192 191]]

 [[163 171 171]
  [162 170 170]
  [160 170 170]
  ...
  [183 191 190]
  [184 192 191]
  [184 192 191]]

 [[162 170 170]
  [162 170 170]
  [162 170 170]
  ...
  [183 191 191]
  [183 19

INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:27] "POST / HTTP/1.1" 200 -


24-05-31 12:20:27 - find function duration 0.6264739036560059 seconds
24-05-31 12:20:27 - Searching [[[164 174 174]
  [162 172 172]
  [160 170 170]
  ...
  [186 192 197]
  [186 192 199]
  [186 192 199]]

 [[163 173 173]
  [162 172 172]
  [162 172 172]
  ...
  [186 192 197]
  [186 192 199]
  [186 192 199]]

 [[161 171 171]
  [163 173 173]
  [164 174 174]
  ...
  [186 192 197]
  [186 192 199]
  [186 192 199]]

 ...

 [[204 206 207]
  [199 204 203]
  [198 203 201]
  ...
  [126 143 152]
  [132 150 157]
  [134 152 159]]

 [[199 202 206]
  [197 201 202]
  [196 202 201]
  ...
  [138 155 164]
  [129 147 154]
  [131 149 156]]

 [[201 204 208]
  [200 205 206]
  [199 204 205]
  ...
  [154 171 180]
  [130 148 155]
  [133 151 158]]] in 36 length datastore
24-05-31 12:20:28 - Searching [[[168 179 177]
  [166 177 175]
  [165 175 175]
  ...
  [189 194 197]
  [189 193 198]
  [189 193 198]]

 [[167 178 176]
  [166 177 175]
  [165 175 175]
  ...
  [189 194 197]
  [189 193 198]
  [189 193 198]]

 [[166 17

INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:28] "POST / HTTP/1.1" 200 -


24-05-31 12:20:28 - find function duration 1.261042833328247 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:29] "POST / HTTP/1.1" 200 -


24-05-31 12:20:29 - find function duration 0.78955078125 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:29] "POST / HTTP/1.1" 200 -


24-05-31 12:20:29 - Searching [[[170 175 178]
  [169 174 177]
  [168 173 176]
  ...
  [189 197 197]
  [190 198 198]
  [190 198 198]]

 [[170 175 178]
  [169 174 177]
  [168 173 176]
  ...
  [190 198 198]
  [190 198 198]
  [190 198 198]]

 [[170 175 178]
  [169 174 177]
  [168 173 176]
  ...
  [190 198 198]
  [189 197 197]
  [189 197 197]]

 ...

 [[205 207 195]
  [203 205 193]
  [200 204 193]
  ...
  [163 171 161]
  [195 203 192]
  [204 212 201]]

 [[206 208 196]
  [204 206 194]
  [201 205 194]
  ...
  [162 170 160]
  [189 197 186]
  [202 210 199]]

 [[207 209 197]
  [205 207 195]
  [201 205 194]
  ...
  [165 173 163]
  [185 193 182]
  [197 205 194]]] in 36 length datastore
24-05-31 12:20:30 - Searching [[[175 174 176]
  [175 174 176]
  [175 174 176]
  ...
  [192 196 201]
  [191 195 200]
  [190 194 199]]

 [[176 175 177]
  [175 174 176]
  [174 173 175]
  ...
  [191 195 200]
  [190 194 199]
  [190 194 199]]

 [[176 175 177]
  [175 174 176]
  [172 174 175]
  ...
  [191 195 200]
  [190 19

INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:31] "POST / HTTP/1.1" 200 -


24-05-31 12:20:31 - find function duration 0.5876686573028564 seconds
24-05-31 12:20:31 - Searching [[[174 176 184]
  [175 177 185]
  [175 178 186]
  ...
  [193 196 200]
  [194 198 199]
  [194 198 199]]

 [[174 176 184]
  [173 175 183]
  [171 174 182]
  ...
  [194 197 201]
  [194 198 199]
  [194 198 199]]

 [[174 177 185]
  [172 175 183]
  [170 173 181]
  ...
  [193 198 201]
  [193 198 199]
  [193 198 199]]

 ...

 [[202 209 196]
  [201 208 195]
  [198 206 195]
  ...
  [172 177 168]
  [195 201 190]
  [202 208 197]]

 [[202 208 197]
  [201 207 196]
  [199 207 196]
  ...
  [170 175 166]
  [190 195 186]
  [203 208 199]]

 [[202 208 197]
  [201 207 196]
  [199 207 196]
  ...
  [171 176 167]
  [186 191 182]
  [201 206 197]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:31] "POST / HTTP/1.1" 200 -


24-05-31 12:20:31 - find function duration 0.604611873626709 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:32] "POST / HTTP/1.1" 200 -


24-05-31 12:20:32 - Searching [[[180 178 184]
  [179 177 183]
  [178 176 182]
  ...
  [195 202 205]
  [195 202 205]
  [195 202 205]]

 [[180 178 184]
  [180 178 184]
  [179 177 183]
  ...
  [194 201 204]
  [194 201 204]
  [194 201 204]]

 [[179 180 184]
  [178 179 183]
  [178 178 184]
  ...
  [192 199 202]
  [193 200 203]
  [194 201 204]]

 ...

 [[207 208 198]
  [207 208 198]
  [205 208 199]
  ...
  [176 179 177]
  [205 207 207]
  [207 209 210]]

 [[208 209 200]
  [207 208 199]
  [204 206 200]
  ...
  [175 178 176]
  [201 203 203]
  [203 205 206]]

 [[208 209 200]
  [207 208 199]
  [204 206 200]
  ...
  [179 182 180]
  [200 202 202]
  [199 201 202]]] in 36 length datastore
24-05-31 12:20:33 - Searching [[[174 180 179]
  [173 179 178]
  [173 180 177]
  ...
  [195 200 209]
  [196 200 211]
  [196 200 211]]

 [[174 180 179]
  [174 180 179]
  [174 180 179]
  ...
  [195 200 209]
  [195 199 210]
  [196 200 211]]

 [[175 180 181]
  [175 181 180]
  [175 181 180]
  ...
  [194 199 208]
  [193 20

INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:34] "POST / HTTP/1.1" 200 -


24-05-31 12:20:34 - find function duration 0.5939345359802246 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:34] "POST / HTTP/1.1" 200 -


24-05-31 12:20:34 - Searching [[[173 179 184]
  [173 179 184]
  [173 180 183]
  ...
  [192 200 207]
  [192 200 207]
  [192 200 207]]

 [[172 178 183]
  [172 178 183]
  [172 179 182]
  ...
  [192 200 207]
  [192 200 207]
  [192 200 207]]

 [[173 179 184]
  [173 179 184]
  [173 180 183]
  ...
  [193 201 208]
  [193 201 208]
  [193 201 208]]

 ...

 [[176 185 194]
  [176 187 195]
  [179 188 197]
  ...
  [178 184 173]
  [202 207 198]
  [205 210 201]]

 [[180 186 197]
  [179 188 198]
  [181 188 197]
  ...
  [173 179 168]
  [196 202 191]
  [206 212 201]]

 [[179 185 196]
  [179 185 196]
  [180 187 196]
  ...
  [175 181 170]
  [192 198 187]
  [205 211 200]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:35] "POST / HTTP/1.1" 200 -


24-05-31 12:20:35 - Searching [[[182 184 192]
  [180 183 188]
  [179 183 188]
  ...
  [203 208 209]
  [203 208 209]
  [204 209 210]]

 [[181 183 191]
  [180 183 188]
  [178 182 187]
  ...
  [203 208 209]
  [204 209 210]
  [204 209 210]]

 [[181 183 191]
  [180 183 188]
  [179 183 188]
  ...
  [201 208 211]
  [202 210 210]
  [203 211 211]]

 ...

 [[210 212 200]
  [208 212 200]
  [208 212 200]
  ...
  [182 190 180]
  [202 210 200]
  [214 222 212]]

 [[209 214 199]
  [209 214 199]
  [209 213 201]
  ...
  [181 189 179]
  [200 208 198]
  [213 221 211]]

 [[210 215 200]
  [210 215 200]
  [207 214 201]
  ...
  [183 191 181]
  [197 205 195]
  [206 214 204]]] in 36 length datastore
24-05-31 12:20:36 - Searching [[[184 189 188]
  [183 188 187]
  [180 186 185]
  ...
  [198 210 212]
  [198 210 212]
  [198 210 212]]

 [[182 187 186]
  [182 187 186]
  [181 187 186]
  ...
  [198 210 212]
  [197 209 211]
  [197 209 211]]

 [[180 186 185]
  [180 186 185]
  [181 187 186]
  ...
  [199 208 211]
  [199 20

INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:37] "POST / HTTP/1.1" 200 -


24-05-31 12:20:37 - find function duration 0.9970650672912598 seconds
24-05-31 12:20:37 - Searching [[[180 190 190]
  [179 189 189]
  [178 188 188]
  ...
  [203 208 207]
  [205 208 206]
  [206 209 207]]

 [[179 189 189]
  [179 189 189]
  [178 188 188]
  ...
  [203 208 207]
  [205 208 206]
  [206 209 207]]

 [[178 188 188]
  [179 189 189]
  [179 189 189]
  ...
  [204 209 208]
  [206 208 208]
  [206 208 208]]

 ...

 [[218 216 206]
  [218 216 206]
  [216 215 205]
  ...
  [185 186 176]
  [215 213 205]
  [223 221 213]]

 [[218 216 206]
  [219 217 207]
  [216 214 206]
  ...
  [185 186 176]
  [215 214 204]
  [221 220 210]]

 [[219 217 207]
  [219 217 207]
  [216 214 206]
  ...
  [189 190 180]
  [214 213 203]
  [213 212 202]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:37] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:38] "POST / HTTP/1.1" 200 -


24-05-31 12:20:38 - Searching [[[180 186 191]
  [179 185 190]
  [179 185 190]
  ...
  [203 207 212]
  [205 208 213]
  [205 208 213]]

 [[180 186 191]
  [180 186 191]
  [181 187 192]
  ...
  [203 207 212]
  [204 207 212]
  [204 207 212]]

 [[180 186 191]
  [181 187 192]
  [182 189 192]
  ...
  [204 207 212]
  [204 207 212]
  [204 207 212]]

 ...

 [[220 220 206]
  [218 218 204]
  [216 217 207]
  ...
  [195 199 188]
  [217 220 211]
  [218 221 212]]

 [[220 220 206]
  [218 218 204]
  [216 217 207]
  ...
  [186 190 179]
  [213 217 206]
  [209 213 202]]

 [[219 219 205]
  [217 217 203]
  [216 217 207]
  ...
  [182 186 175]
  [214 218 207]
  [206 210 199]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:39] "POST / HTTP/1.1" 200 -


24-05-31 12:20:39 - Searching [[[188 190 191]
  [186 188 189]
  [182 187 186]
  ...
  [204 208 213]
  [204 207 215]
  [204 207 215]]

 [[189 191 192]
  [187 189 190]
  [183 188 187]
  ...
  [204 208 213]
  [204 207 215]
  [204 207 215]]

 [[189 191 192]
  [187 189 190]
  [184 188 189]
  ...
  [203 208 211]
  [203 207 212]
  [203 207 212]]

 ...

 [[220 218 208]
  [220 218 208]
  [219 217 209]
  ...
  [193 197 191]
  [212 214 208]
  [213 215 209]]

 [[220 218 208]
  [220 218 208]
  [219 217 209]
  ...
  [188 192 186]
  [217 219 213]
  [216 218 212]]

 [[220 218 208]
  [220 218 208]
  [219 217 209]
  ...
  [185 189 183]
  [216 218 212]
  [213 215 209]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:40] "POST / HTTP/1.1" 200 -


24-05-31 12:20:40 - Searching [[[187 190 194]
  [186 189 193]
  [186 190 191]
  ...
  [206 211 212]
  [206 211 212]
  [206 211 212]]

 [[187 190 194]
  [187 190 194]
  [186 190 191]
  ...
  [206 211 212]
  [206 211 212]
  [206 211 212]]

 [[187 192 195]
  [186 191 194]
  [185 190 191]
  ...
  [206 211 212]
  [206 211 212]
  [206 211 212]]

 ...

 [[218 222 210]
  [216 220 208]
  [214 220 209]
  ...
  [195 200 191]
  [216 219 210]
  [216 219 210]]

 [[219 223 212]
  [217 221 210]
  [214 220 209]
  ...
  [192 195 186]
  [218 221 212]
  [214 217 208]]

 [[221 225 214]
  [218 222 211]
  [215 221 210]
  ...
  [189 192 183]
  [221 224 215]
  [213 216 207]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:41] "POST / HTTP/1.1" 200 -


24-05-31 12:20:41 - Searching [[[184 191 194]
  [184 191 194]
  [184 192 192]
  ...
  [205 211 216]
  [205 211 216]
  [205 211 216]]

 [[184 191 194]
  [184 191 194]
  [184 192 192]
  ...
  [205 211 216]
  [205 211 216]
  [205 211 216]]

 [[184 191 194]
  [184 191 194]
  [184 192 192]
  ...
  [205 211 216]
  [205 211 216]
  [205 211 216]]

 ...

 [[222 223 214]
  [219 222 213]
  [219 222 213]
  ...
  [194 198 192]
  [211 212 208]
  [215 216 212]]

 [[220 223 214]
  [219 222 213]
  [218 221 212]
  ...
  [191 192 188]
  [206 207 203]
  [209 210 206]]

 [[220 223 214]
  [219 222 213]
  [216 221 212]
  ...
  [196 197 193]
  [210 211 207]
  [213 214 210]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:42] "POST / HTTP/1.1" 200 -


24-05-31 12:20:42 - Searching [[[181 193 193]
  [180 192 192]
  [179 191 191]
  ...
  [204 210 215]
  [204 210 217]
  [204 210 217]]

 [[181 193 193]
  [180 192 192]
  [180 192 192]
  ...
  [204 210 215]
  [204 210 217]
  [204 210 217]]

 [[181 193 193]
  [181 193 193]
  [180 192 192]
  ...
  [204 210 215]
  [204 210 217]
  [204 210 217]]

 ...

 [[224 222 211]
  [223 221 210]
  [220 220 208]
  ...
  [187 193 182]
  [213 219 208]
  [212 218 207]]

 [[224 222 211]
  [224 222 211]
  [221 220 210]
  ...
  [185 194 181]
  [212 221 208]
  [211 220 207]]

 [[223 221 210]
  [224 222 211]
  [222 221 211]
  ...
  [185 194 181]
  [210 219 206]
  [207 216 203]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:43] "POST / HTTP/1.1" 200 -


24-05-31 12:20:43 - Searching [[[185 191 196]
  [185 191 196]
  [185 191 196]
  ...
  [203 211 210]
  [204 212 211]
  [204 212 211]]

 [[185 191 196]
  [185 191 196]
  [185 191 196]
  ...
  [203 211 210]
  [204 212 211]
  [204 212 211]]

 [[185 191 196]
  [185 191 196]
  [185 191 196]
  ...
  [203 211 210]
  [204 212 211]
  [204 212 211]]

 ...

 [[221 218 213]
  [220 220 214]
  [217 217 211]
  ...
  [192 200 190]
  [216 223 216]
  [210 217 210]]

 [[219 218 214]
  [220 219 215]
  [218 217 213]
  ...
  [190 197 190]
  [212 219 212]
  [212 219 212]]

 [[219 218 214]
  [220 219 215]
  [216 217 213]
  ...
  [188 195 188]
  [208 215 208]
  [211 218 211]]] in 36 length datastore
24-05-31 12:20:44 - Searching [[[184 190 197]
  [184 190 197]
  [184 190 195]
  ...
  [203 210 213]
  [206 211 214]
  [206 211 214]]

 [[184 190 197]
  [184 190 197]
  [184 190 195]
  ...
  [203 210 213]
  [205 210 213]
  [206 211 214]]

 [[184 190 197]
  [184 190 197]
  [184 190 195]
  ...
  [205 210 213]
  [205 21

INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:45] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:45] "POST / HTTP/1.1" 200 -


24-05-31 12:20:45 - find function duration 0.5647594928741455 seconds
24-05-31 12:20:45 - Searching [[[182 192 186]
  [183 193 187]
  [184 194 188]
  ...
  [203 211 211]
  [203 211 211]
  [203 211 211]]

 [[182 192 186]
  [183 193 187]
  [183 193 187]
  ...
  [203 211 211]
  [203 211 211]
  [203 211 211]]

 [[184 193 190]
  [184 193 190]
  [184 193 190]
  ...
  [203 211 211]
  [202 210 210]
  [202 210 210]]

 ...

 [[216 220 209]
  [215 219 208]
  [215 218 209]
  ...
  [189 195 184]
  [217 220 211]
  [218 221 212]]

 [[214 220 209]
  [213 219 208]
  [214 219 210]
  ...
  [184 190 179]
  [217 220 211]
  [218 221 212]]

 [[215 221 210]
  [214 220 209]
  [213 221 211]
  ...
  [184 190 179]
  [216 219 210]
  [218 221 212]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 12:20:46] "POST / HTTP/1.1" 200 -


24-05-31 12:20:46 - Searching [[[183 194 191]
  [182 193 190]
  [181 192 190]
  ...
  [197 206 209]
  [197 206 209]
  [200 209 212]]

 [[181 192 189]
  [180 191 188]
  [178 189 187]
  ...
  [197 206 209]
  [197 206 209]
  [199 208 211]]

 [[182 193 191]
  [180 191 189]
  [179 189 189]
  ...
  [197 206 209]
  [197 206 209]
  [199 208 211]]

 ...

 [[215 219 208]
  [214 218 207]
  [214 217 208]
  ...
  [193 199 188]
  [213 219 208]
  [212 218 207]]

 [[215 218 209]
  [214 217 208]
  [214 217 208]
  ...
  [194 200 189]
  [210 216 205]
  [212 218 207]]

 [[215 218 209]
  [214 217 208]
  [214 217 208]
  ...
  [196 202 191]
  [205 211 200]
  [209 215 204]]] in 36 length datastore
