<a href="https://colab.research.google.com/github/nilu-ai/Restaurant_Fttx_project/blob/main/Pre%20trained%20Model%20wala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install deepface

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.3/97.3 kB 1.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 14.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.4/88.4 kB 12.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 11.4 MB/s eta 0:00:00
  Created wheel for fire: filename=fire-0.6.0-py2.py3-none-any.whl size=117029 sha256=16b140ea6e9e47bbbba9cb4d0d6178b71dc65a72bcad25011959287855b34682
  Stored in directory: /root/.cache/pip/wheels/d6/6d/5d/5b73fa0f46d01a793713f8859201361e9e581ced8c75e5c6a3
Successfully built fire


In [2]:
!unzip trainss

Archive:  trainss.zip
   creating: trainss/abhi/
  inflating: trainss/abhi/WIN_20240524_15_28_37_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_39_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_41_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_42_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_44_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_45_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_47_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_48_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_50_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_52_Pro.jpg  
   creating: trainss/Abhishek 1/
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_24_Pro (2).jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_24_Pro.jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_25_Pro (2).jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_25_Pro.jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_29_22_Pro.jpg  
  inflatin

In [19]:
from deepface import DeepFace
df = DeepFace.find(img_path = "/content/WIN_20240531_13_34_12_Pro.jpg", db_path = "/content/trainss",model_name="Facenet512")
print(df)
if df[0].distance.empty:
  print("Unkonw")
elif df[0].distance[0]<0.3:
  print(df)
else:
  print("Unkonw")



24-05-31 08:07:10 - Searching /content/WIN_20240531_13_34_12_Pro.jpg in 34 length datastore
24-05-31 08:07:11 - find function duration 0.7983593940734863 seconds
[Empty DataFrame
Columns: [identity, hash, target_x, target_y, target_w, target_h, source_x, source_y, source_w, source_h, threshold, distance]
Index: []]
Unkonw


In [11]:
from flask import Flask, request, jsonify
import cv2
import numpy as np
import base64
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from google.colab.patches import cv2_imshow
from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(5000)"))
app = Flask(__name__)


# Dictionary which assigns each label an emotion



def predict_emotion(face_img):
    predict=DeepFace.find(img_path = face_img, db_path = "/content/Train",model_name="Facenet512")
    print(predict)

@app.route('/', methods=['GET', 'POST'])
def upload_image():
    if request.method == 'POST':
        data = request.json
        img_data = data['image'].split(',')[1]
        nparr = np.frombuffer(base64.b64decode(img_data), np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        # face_images, coordinates = detect_and_extract_faces(img, face_cascade)

        # predictions = []
        # for face_img, (x, y, w, h) in zip(face_images, coordinates):
        #     cv2.flip(face_img,0)
        #     cv2_imshow(face_img)

        #     label, confidence = predict_emotion(face_img)
        #     print(predict_emotion(face_img))
        #     predictions.append({
        #         'label': label,
        #         'confidence': confidence,

        #     })
        df="unknow"
        predict=DeepFace.find(img_path = img, db_path = "/content/trainss",model_name="Facenet512")
        if predict[0].distance.empty:
          print("Unkonw")
        elif predict[0].distance[0]<0.3:
          print(df)
          df=predict
        else:
          print("Unkonw")

        return jsonify(df)
    return """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <video id="video" width="640" height="480" autoplay></video>
        <canvas id="canvas" width="640" height="480" style="display:none;"></canvas>
        <div id="prediction"></div>
        <script>
            const video = document.getElementById('video');
            const canvas = document.getElementById('canvas');
            const predictionDiv = document.getElementById('prediction');

            async function initCamera() {
                try {
                    const stream = await navigator.mediaDevices.getUserMedia({ video: true });
                    video.srcObject = stream;
                } catch (err) {
                    console.error('Error accessing camera:', err);
                }
            }

            async function captureAndPredict() {
                const context = canvas.getContext('2d');
                context.drawImage(video, 0, 0, canvas.width, canvas.height);
                const imageData = canvas.toDataURL('image/jpeg');
                const response = await fetch('/', {
                    method: 'POST',
                    body: JSON.stringify({ image: imageData }),
                    headers: {
                        'Content-Type': 'application/json'
                    }
                });
                const result = await response.json();

                predictionDiv.innerHTML = JSON.stringify(result, null, 2);
            }

            setInterval(captureAndPredict, 1000);

            initCamera();
        </script>
    </body>
    </html>
    """

if __name__ == '__main__':
    app.run(host='0.0.0.0')


https://svbiubpeh6b-496ff2e9c6d22116-5000-colab.googleusercontent.com/
 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.28.0.12:5000
INFO:werkzeug:Press CTRL+C to quit


24-05-31 08:03:35 - Found 1 newly added image(s), 0 removed image(s), 0 replaced image(s).


Finding representations: 100%|██████████| 1/1 [00:00<00:00,  1.59it/s]
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-11-0acd1495442d>", line 44, in upload_image
    predict=DeepFace.find(img_path = img, db_path = "/content/trainss",model_name="Facenet512")
  File "/usr/local/lib/python3.10/dist-packages/deepface/DeepFace.py", line 320, in find
    return recognition.find(
  Fil

24-05-31 08:03:36 - There are now 34 representations in ds_model_facenet512_detector_opencv_aligned_normalization_base_expand_0.pkl
24-05-31 08:03:36 - Searching [[[156 158 152]
  [156 158 152]
  [156 158 152]
  ...
  [231 230 220]
  [231 231 219]
  [231 231 219]]

 [[155 157 151]
  [155 157 151]
  [156 158 152]
  ...
  [230 229 219]
  [230 230 218]
  [230 230 218]]

 [[154 155 151]
  [155 156 152]
  [153 157 152]
  ...
  [229 228 218]
  [229 228 218]
  [229 228 218]]

 ...

 [[160 157 142]
  [159 156 141]
  [158 155 140]
  ...
  [167 179 183]
  [165 177 183]
  [163 175 181]]

 [[160 158 140]
  [159 157 139]
  [158 155 140]
  ...
  [169 181 185]
  [168 178 185]
  [166 176 183]]

 [[163 161 143]
  [161 159 141]
  [158 155 140]
  ...
  [169 181 185]
  [168 178 185]
  [167 177 184]]] in 34 length datastore


ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-11-0acd1495442d>", line 44, in upload_image
    predict=DeepFace.find(img_path = img, db_path = "/content/trainss",model_name="Facenet512")
  File "/usr/local/lib/python3.10/dist-packages/deepface/DeepFace.py", line 320, in find
    return recognition.find(
  File "/usr/local/lib/python3.10/dist-packages/deepface/modules/recognition

24-05-31 08:03:37 - Searching [[[153 160 155]
  [152 159 154]
  [152 159 154]
  ...
  [234 228 223]
  [233 227 222]
  [232 226 221]]

 [[151 158 153]
  [151 158 153]
  [152 159 154]
  ...
  [233 227 222]
  [233 227 222]
  [232 226 221]]

 [[149 156 151]
  [150 157 152]
  [152 159 154]
  ...
  [230 226 221]
  [231 227 222]
  [231 227 222]]

 ...

 [[166 161 146]
  [165 160 145]
  [162 159 144]
  ...
  [163 178 180]
  [162 177 179]
  [163 178 180]]

 [[167 162 147]
  [166 161 146]
  [162 159 144]
  ...
  [164 182 183]
  [166 182 181]
  [166 182 181]]

 [[169 164 149]
  [167 162 147]
  [162 159 144]
  ...
  [165 183 184]
  [166 182 181]
  [166 182 181]]] in 34 length datastore


ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-11-0acd1495442d>", line 44, in upload_image
    predict=DeepFace.find(img_path = img, db_path = "/content/trainss",model_name="Facenet512")
  File "/usr/local/lib/python3.10/dist-packages/deepface/DeepFace.py", line 320, in find
    return recognition.find(
  File "/usr/local/lib/python3.10/dist-packages/deepface/modules/recognition

24-05-31 08:03:37 - Searching [[[159 167 156]
  [157 165 154]
  [155 163 152]
  ...
  [240 232 225]
  [242 232 225]
  [242 232 225]]

 [[157 165 154]
  [157 165 154]
  [156 164 153]
  ...
  [240 232 225]
  [242 232 225]
  [242 232 225]]

 [[156 164 153]
  [156 164 153]
  [157 165 155]
  ...
  [239 231 224]
  [239 231 224]
  [240 232 225]]

 ...

 [[167 164 150]
  [166 163 149]
  [165 161 150]
  ...
  [174 187 189]
  [174 187 189]
  [172 185 187]]

 [[167 164 150]
  [166 163 149]
  [166 163 149]
  ...
  [176 189 191]
  [175 188 190]
  [174 187 189]]

 [[169 166 152]
  [168 165 151]
  [167 164 150]
  ...
  [176 189 191]
  [176 189 191]
  [175 188 190]]] in 34 length datastore
24-05-31 08:03:38 - Searching [[[159 166 161]
  [158 165 160]
  [157 165 158]
  ...
  [240 234 223]
  [240 234 221]
  [240 234 221]]

 [[157 164 159]
  [157 164 159]
  [156 164 157]
  ...
  [240 234 223]
  [240 234 221]
  [240 234 221]]

 [[157 164 159]
  [156 163 158]
  [157 164 157]
  ...
  [237 233 222]
  [237 23

INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:03:39] "POST / HTTP/1.1" 200 -


24-05-31 08:03:39 - find function duration 0.3434619903564453 seconds
Unkonw
24-05-31 08:03:39 - Searching [[[159 165 160]
  [159 165 160]
  [159 165 160]
  ...
  [236 233 225]
  [238 232 225]
  [238 232 225]]

 [[158 164 159]
  [158 164 159]
  [158 164 159]
  ...
  [237 234 226]
  [238 232 225]
  [238 232 225]]

 [[157 163 158]
  [157 163 158]
  [157 163 158]
  ...
  [236 233 225]
  [237 232 223]
  [237 232 223]]

 ...

 [[172 169 148]
  [172 169 148]
  [170 169 149]
  ...
  [175 188 190]
  [174 187 189]
  [173 186 188]]

 [[174 170 146]
  [171 169 145]
  [169 168 147]
  ...
  [176 188 192]
  [175 187 191]
  [174 186 190]]

 [[175 171 147]
  [172 170 146]
  [171 168 147]
  ...
  [176 188 192]
  [176 188 192]
  [175 187 191]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:03:40] "POST / HTTP/1.1" 200 -


24-05-31 08:03:40 - find function duration 0.46514296531677246 seconds
Unkonw
24-05-31 08:03:40 - Searching [[[156 171 163]
  [154 169 161]
  [154 167 159]
  ...
  [240 235 226]
  [240 235 226]
  [241 236 227]]

 [[156 171 163]
  [154 169 161]
  [155 168 160]
  ...
  [239 234 225]
  [240 235 226]
  [241 236 227]]

 [[158 170 164]
  [157 169 163]
  [159 169 163]
  ...
  [241 234 225]
  [242 235 226]
  [242 235 226]]

 ...

 [[180 176 158]
  [174 170 152]
  [171 168 153]
  ...
  [182 197 199]
  [182 197 199]
  [182 197 199]]

 [[179 174 159]
  [174 169 154]
  [172 169 154]
  ...
  [184 199 201]
  [183 198 200]
  [183 198 200]]

 [[178 173 158]
  [173 168 153]
  [171 168 153]
  ...
  [184 199 201]
  [184 199 201]
  [183 198 200]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:03:40] "POST / HTTP/1.1" 200 -


24-05-31 08:03:40 - find function duration 0.4927713871002197 seconds
Unkonw
24-05-31 08:03:41 - Searching [[[173 174 164]
  [171 172 162]
  [169 170 161]
  ...
  [188 192 186]
  [187 192 183]
  [184 189 180]]

 [[173 174 164]
  [172 173 163]
  [172 173 164]
  ...
  [188 192 186]
  [187 192 183]
  [185 190 181]]

 [[172 173 163]
  [173 174 164]
  [174 175 166]
  ...
  [186 190 184]
  [185 189 183]
  [183 187 181]]

 ...

 [[204 203 193]
  [204 203 193]
  [204 202 194]
  ...
  [177 196 201]
  [171 191 196]
  [170 190 195]]

 [[205 204 194]
  [205 204 194]
  [205 203 195]
  ...
  [177 196 201]
  [171 191 196]
  [169 189 194]]

 [[205 204 194]
  [205 204 194]
  [206 204 196]
  ...
  [177 196 201]
  [171 191 196]
  [169 189 194]]] in 34 length datastore


ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-11-0acd1495442d>", line 53, in upload_image
    return jsonify(df)
  File "/usr/local/lib/python3.10/dist-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, *

24-05-31 08:03:42 - find function duration 0.36596250534057617 seconds
unknow
24-05-31 08:03:43 - Searching [[[176 179 164]
  [176 179 164]
  [176 178 166]
  ...
  [192 195 193]
  [193 196 194]
  [192 195 193]]

 [[176 179 164]
  [176 179 164]
  [176 178 166]
  ...
  [190 193 191]
  [191 194 192]
  [190 193 191]]

 [[176 178 166]
  [176 178 166]
  [176 178 166]
  ...
  [190 193 191]
  [191 194 192]
  [190 193 191]]

 ...

 [[204 203 193]
  [204 203 193]
  [204 203 193]
  ...
  [171 192 189]
  [171 192 189]
  [168 189 186]]

 [[205 204 194]
  [205 204 194]
  [205 204 194]
  ...
  [170 192 187]
  [173 195 190]
  [169 191 186]]

 [[206 205 195]
  [206 205 195]
  [205 204 194]
  ...
  [169 191 186]
  [174 196 191]
  [168 190 185]]] in 34 length datastore


ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-11-0acd1495442d>", line 53, in upload_image
    return jsonify(df)
  File "/usr/local/lib/python3.10/dist-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, *

24-05-31 08:03:43 - find function duration 0.4483039379119873 seconds
unknow
24-05-31 08:03:44 - Searching [[[171 176 167]
  [179 184 175]
  [183 188 179]
  ...
  [195 198 196]
  [195 199 194]
  [194 198 193]]

 [[171 176 167]
  [175 180 171]
  [178 183 174]
  ...
  [195 199 194]
  [193 197 192]
  [192 196 191]]

 [[172 176 170]
  [171 175 169]
  [174 179 170]
  ...
  [194 198 193]
  [192 196 191]
  [190 194 188]]

 ...

 [[203 204 194]
  [203 204 194]
  [203 204 194]
  ...
  [172 194 200]
  [171 193 199]
  [169 191 197]]

 [[204 206 194]
  [204 206 194]
  [204 206 194]
  ...
  [172 196 202]
  [170 193 201]
  [166 189 197]]

 [[206 208 196]
  [206 208 196]
  [206 208 196]
  ...
  [172 196 202]
  [169 192 200]
  [164 187 195]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:03:44] "POST / HTTP/1.1" 200 -


24-05-31 08:03:44 - find function duration 0.3831660747528076 seconds
Unkonw
24-05-31 08:03:45 - Searching [[[177 177 171]
  [177 177 171]
  [177 177 171]
  ...
  [197 199 200]
  [196 197 201]
  [195 196 200]]

 [[177 177 171]
  [177 177 171]
  [177 177 171]
  ...
  [195 197 198]
  [193 194 198]
  [192 193 197]]

 [[175 177 171]
  [175 177 171]
  [175 177 171]
  ...
  [192 194 195]
  [191 193 194]
  [190 192 193]]

 ...

 [[202 206 195]
  [202 206 195]
  [202 206 195]
  ...
  [181 202 204]
  [179 200 202]
  [174 195 197]]

 [[202 206 194]
  [202 206 194]
  [203 207 195]
  ...
  [183 203 208]
  [177 200 202]
  [172 195 197]]

 [[202 206 194]
  [203 207 195]
  [203 207 195]
  ...
  [184 204 209]
  [177 200 202]
  [171 194 196]]] in 34 length datastore


ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-11-0acd1495442d>", line 53, in upload_image
    return jsonify(df)
  File "/usr/local/lib/python3.10/dist-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, *

24-05-31 08:03:45 - find function duration 0.39608097076416016 seconds
unknow


ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-11-0acd1495442d>", line 44, in upload_image
    predict=DeepFace.find(img_path = img, db_path = "/content/trainss",model_name="Facenet512")
  File "/usr/local/lib/python3.10/dist-packages/deepface/DeepFace.py", line 320, in find
    return recognition.find(
  File "/usr/local/lib/python3.10/dist-packages/deepface/modules/recognition

24-05-31 08:03:46 - Searching [[[183 178 175]
  [182 177 174]
  [181 176 173]
  ...
  [193 197 192]
  [193 197 191]
  [192 196 190]]

 [[183 178 175]
  [182 177 174]
  [181 176 173]
  ...
  [196 200 195]
  [195 199 193]
  [194 198 192]]

 [[181 178 174]
  [181 178 174]
  [181 178 174]
  ...
  [195 199 194]
  [192 196 191]
  [191 195 190]]

 ...

 [[206 204 194]
  [206 204 194]
  [206 205 195]
  ...
  [185 204 209]
  [179 198 203]
  [178 197 202]]

 [[209 206 198]
  [209 206 198]
  [208 206 198]
  ...
  [186 205 210]
  [179 198 203]
  [179 198 203]]

 [[210 207 199]
  [210 207 199]
  [209 207 199]
  ...
  [188 207 212]
  [181 200 205]
  [182 201 206]]] in 34 length datastore
24-05-31 08:03:47 - Searching [[[176 182 165]
  [176 182 165]
  [176 182 165]
  ...
  [204 199 200]
  [204 199 200]
  [203 198 199]]

 [[177 183 166]
  [177 183 166]
  [177 183 166]
  ...
  [203 198 199]
  [202 197 198]
  [200 195 196]]

 [[179 182 167]
  [179 182 167]
  [179 182 167]
  ...
  [198 196 196]
  [198 19

ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-11-0acd1495442d>", line 53, in upload_image
    return jsonify(df)
  File "/usr/local/lib/python3.10/dist-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, *

24-05-31 08:03:47 - find function duration 0.3942909240722656 seconds
unknow
24-05-31 08:03:48 - Searching [[[185 183 173]
  [185 183 173]
  [184 183 173]
  ...
  [196 203 200]
  [196 203 200]
  [197 204 201]]

 [[186 184 174]
  [185 183 173]
  [184 183 173]
  ...
  [196 203 200]
  [196 203 200]
  [196 203 200]]

 [[185 184 174]
  [185 184 174]
  [184 183 173]
  ...
  [195 202 199]
  [194 201 198]
  [194 201 198]]

 ...

 [[212 210 202]
  [212 210 202]
  [212 210 202]
  ...
  [188 207 210]
  [187 206 209]
  [177 196 199]]

 [[212 210 202]
  [212 210 202]
  [212 210 202]
  ...
  [188 209 211]
  [188 207 210]
  [184 203 206]]

 [[212 210 202]
  [212 210 202]
  [212 210 202]
  ...
  [191 212 214]
  [187 206 209]
  [185 204 207]]] in 34 length datastore


ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-11-0acd1495442d>", line 53, in upload_image
    return jsonify(df)
  File "/usr/local/lib/python3.10/dist-packages/flask/json/__init__.py", line 342, in jsonify
    return current_app.json.response(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/json/provider.py", line 309, in response
    f"{self.dumps(obj, *

24-05-31 08:03:48 - find function duration 0.37514209747314453 seconds
unknow


ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "<ipython-input-11-0acd1495442d>", line 44, in upload_image
    predict=DeepFace.find(img_path = img, db_path = "/content/trainss",model_name="Facenet512")
  File "/usr/local/lib/python3.10/dist-packages/deepface/DeepFace.py", line 320, in find
    return recognition.find(
  File "/usr/local/lib/python3.10/dist-packages/deepface/modules/recognition

24-05-31 08:03:49 - Searching [[[185 185 173]
  [185 185 173]
  [184 183 173]
  ...
  [203 203 203]
  [203 203 203]
  [202 202 202]]

 [[185 185 173]
  [185 185 173]
  [184 183 173]
  ...
  [202 202 202]
  [201 201 201]
  [200 200 200]]

 [[185 185 173]
  [185 185 173]
  [183 184 174]
  ...
  [201 202 200]
  [199 200 198]
  [197 198 196]]

 ...

 [[208 209 199]
  [208 209 199]
  [209 210 200]
  ...
  [181 199 200]
  [186 201 204]
  [182 197 200]]

 [[211 209 201]
  [211 209 201]
  [211 209 201]
  ...
  [181 198 201]
  [183 200 203]
  [179 196 199]]

 [[211 209 201]
  [211 209 201]
  [211 209 201]
  ...
  [183 200 203]
  [183 200 203]
  [179 196 199]]] in 34 length datastore
24-05-31 08:03:50 - Searching [[[181 185 174]
  [181 185 174]
  [179 185 174]
  ...
  [222 225 216]
  [222 224 218]
  [222 224 218]]

 [[181 185 174]
  [181 185 174]
  [179 185 174]
  ...
  [221 224 215]
  [222 224 218]
  [222 224 218]]

 [[181 185 174]
  [181 185 174]
  [179 184 175]
  ...
  [223 224 215]
  [223 22

INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:03:50] "POST / HTTP/1.1" 200 -


24-05-31 08:03:50 - find function duration 0.3465123176574707 seconds
Unkonw
24-05-31 08:03:51 - Searching [[[173 184 176]
  [173 184 176]
  [173 184 176]
  ...
  [222 221 211]
  [222 221 211]
  [221 220 210]]

 [[173 184 176]
  [173 184 176]
  [173 184 176]
  ...
  [220 219 209]
  [221 220 210]
  [222 221 211]]

 [[176 184 177]
  [176 184 177]
  [176 184 177]
  ...
  [219 217 209]
  [220 218 210]
  [221 219 211]]

 ...

 [[224 213 186]
  [222 213 186]
  [219 209 185]
  ...
  [217 234 231]
  [215 230 232]
  [214 229 231]]

 [[225 214 186]
  [222 213 186]
  [218 208 184]
  ...
  [219 233 231]
  [215 230 232]
  [212 227 229]]

 [[223 212 184]
  [220 212 183]
  [218 208 184]
  ...
  [221 235 233]
  [216 231 233]
  [213 228 230]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:03:51] "POST / HTTP/1.1" 200 -


24-05-31 08:03:51 - find function duration 0.428363561630249 seconds
Unkonw
24-05-31 08:03:52 - Searching [[[177 187 175]
  [176 186 174]
  [176 186 174]
  ...
  [219 219 213]
  [219 218 214]
  [218 217 213]]

 [[176 186 174]
  [176 186 174]
  [176 186 174]
  ...
  [219 219 213]
  [218 217 213]
  [218 217 213]]

 [[175 184 174]
  [175 184 174]
  [176 186 174]
  ...
  [218 218 212]
  [218 217 213]
  [218 217 213]]

 ...

 [[218 211 186]
  [220 213 186]
  [217 212 181]
  ...
  [223 235 229]
  [219 233 229]
  [219 234 230]]

 [[217 209 186]
  [220 213 188]
  [217 212 181]
  ...
  [223 235 229]
  [219 233 229]
  [219 233 229]]

 [[219 211 188]
  [222 215 190]
  [216 211 180]
  ...
  [224 237 229]
  [221 235 231]
  [219 233 229]]] in 34 length datastore


In [11]:
df.verify(img_path ="/content/WIN_20240524_17_49_35_Pro.jpg")

AttributeError: 'list' object has no attribute 'verify'

In [6]:
new_df=DeepFace.stream(db_path = "/content/Train")


24-05-31 05:40:09 - age_model_weights.h5 will be downloaded...


Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/age_model_weights.h5
To: /root/.deepface/weights/age_model_weights.h5
100%|██████████| 539M/539M [00:02<00:00, 207MB/s]


24-05-31 05:40:14 - Age model is just built
24-05-31 05:40:16 - gender_model_weights.h5 will be downloaded...


Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/gender_model_weights.h5
To: /root/.deepface/weights/gender_model_weights.h5
100%|██████████| 537M/537M [00:08<00:00, 63.7MB/s]


24-05-31 05:40:27 - Gender model is just built
24-05-31 05:40:27 - facial_expression_model_weights.h5 will be downloaded...


Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/facial_expression_model_weights.h5
To: /root/.deepface/weights/facial_expression_model_weights.h5
100%|██████████| 5.98M/5.98M [00:00<00:00, 21.0MB/s]


24-05-31 05:40:28 - Emotion model is just built
24-05-31 05:40:28 - VGG-Face is built


In [29]:

import pickle
model = pickle.load(open('/content/Train/ds_model_facenet512_detector_opencv_aligned_normalization_base_expand_0.pkl','rb'))

AttributeError: 'list' object has no attribute 'predict'

In [21]:
import pickle
import numpy as np
from PIL import Image
import cv2

# Step 1: Load the saved model
with open('/content/Train/ds_model_facenet512_detector_opencv_aligned_normalization_base_expand_0.pkl', 'rb') as file:
    model = pickle.load(file)

# Step 2: Preprocess the new image
def preprocess_image(image_path):
    # Load image
    image = Image.open(image_path)
    image = image.convert('RGB')
    # Resize image to the size expected by the FaceNet model (usually 160x160)
    image = image.resize((160, 160))
    # Convert image to numpy array
    image = np.array(image)
    # Normalize the image (as per the normalization done during training)
    image = image.astype('float32')
    mean, std = image.mean(), image.std()
    image = (image - mean) / std
    # Expand dimensions to match the input shape of the model (batch size, height, width, channels)
    image = np.expand_dims(image, axis=0)
    return image

# Path to the new image
new_image_path = '/content/WIN_20240514_09_48_51_Pro.jpg'
# Preprocess the new image
processed_image = preprocess_image(new_image_path)
pre=model.predict(processed_image)
print(pre)


FileNotFoundError: [Errno 2] No such file or directory: '/content/Train/ds_model_facenet512_detector_opencv_aligned_normalization_base_expand_0.pkl'

In [22]:
from flask import Flask, request, jsonify
import cv2
import numpy as np
import base64
from deepface import DeepFace  # Ensure you have deepface installed

app = Flask(__name__)

@app.route('/', methods=['GET', 'POST'])
def upload_image():
    if request.method == 'POST':
        data = request.json
        img_data = data['image'].split(',')[1]
        nparr = np.frombuffer(base64.b64decode(img_data), np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

        try:
            # Perform face recognition using DeepFace
            predictions = DeepFace.find(img_path=img, db_path="/content/trainss", model_name="Facenet512")

            if not predictions[0].empty and predictions[0].distance[0] < 0.3:
                response = {
                    'status': 'success',
                    'data': predictions[0].to_dict()
                }
            else:
                response = {
                    'status': 'unknown'
                }
        except Exception as e:
            response = {
                'status': 'error',
                'message': str(e)
            }

        return jsonify(response)

    return """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <video id="video" width="640" height="480" autoplay></video>
        <canvas id="canvas" width="640" height="480" style="display:none;"></canvas>
        <div id="prediction"></div>
        <script>
            const video = document.getElementById('video');
            const canvas = document.getElementById('canvas');
            const predictionDiv = document.getElementById('prediction');

            async function initCamera() {
                try {
                    const stream = await navigator.mediaDevices.getUserMedia({ video: true });
                    video.srcObject = stream;
                } catch (err) {
                    console.error('Error accessing camera:', err);
                }
            }

            async function captureAndPredict() {
                const context = canvas.getContext('2d');
                context.drawImage(video, 0, 0, canvas.width, canvas.height);
                const imageData = canvas.toDataURL('image/jpeg');
                const response = await fetch('/', {
                    method: 'POST',
                    body: JSON.stringify({ image: imageData }),
                    headers: {
                        'Content-Type': 'application/json'
                    }
                });
                const result = await response.json();
                predictionDiv.innerHTML = JSON.stringify(result, null, 2);
            }

            setInterval(captureAndPredict, 1000);

            initCamera();
        </script>
    </body>
    </html>
    """

if __name__ == '__main__':
    app.run(host='0.0.0.0')


 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.28.0.12:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:01] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:02] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:02] "POST / HTTP/1.1" 200 -


24-05-31 08:52:02 - Searching [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:03] "POST / HTTP/1.1" 200 -


24-05-31 08:52:03 - Searching [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:05] "POST / HTTP/1.1" 200 -


24-05-31 08:52:05 - Searching [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]] in 34 length datastore
24-05-31 08:52:05 - Searching [[[133 141 140]
  [133 141 140]
  [132 140 140]
  ...
  [223 223 217]
  [223 223 217]
  [223 223 217]]

 [[134 142 141]
  [134 142 141]
  [134 142 142]
  ...
  [222 222 216]
  [222 222 216]
  [222 222 216]]

 [[134 142 141]
  [134 142 141]
  [134 142 141]
  ...
  [223 220 215]
  [223 220 215]
  [223 220 215]]

 ...

 [[116 116 100]
  [127 127 109]
  [149 149 131]
  ...
  [144 167 169]
  [145 168 170]
  [147 170 172]]

 [[115 113  95]
  [133 131 113]
  [154 154 136]
  ...
  [147 171 171]
  [147 170 

INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:06] "POST / HTTP/1.1" 200 -


24-05-31 08:52:06 - find function duration 0.33303189277648926 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:07] "POST / HTTP/1.1" 200 -


24-05-31 08:52:07 - Searching [[[135 146 136]
  [134 145 135]
  [133 144 136]
  ...
  [159 171 165]
  [160 172 166]
  [160 172 166]]

 [[134 145 137]
  [133 144 136]
  [133 144 136]
  ...
  [159 171 165]
  [160 172 166]
  [160 172 166]]

 [[132 144 138]
  [131 143 137]
  [131 143 137]
  ...
  [160 172 166]
  [160 172 166]
  [161 173 167]]

 ...

 [[ 63  79  95]
  [ 65  81  97]
  [ 66  82  99]
  ...
  [ 34  42  49]
  [ 35  43  50]
  [ 31  39  46]]

 [[ 62  78  94]
  [ 64  80  96]
  [ 65  81  98]
  ...
  [ 33  41  48]
  [ 33  41  48]
  [ 29  37  44]]

 [[ 62  78  94]
  [ 63  79  95]
  [ 64  80  97]
  ...
  [ 31  39  46]
  [ 30  38  45]
  [ 26  34  41]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:08] "POST / HTTP/1.1" 200 -


24-05-31 08:52:08 - Searching [[[143 154 146]
  [141 152 144]
  [139 150 142]
  ...
  [171 180 177]
  [173 182 179]
  [174 183 180]]

 [[144 155 147]
  [142 153 145]
  [140 151 143]
  ...
  [171 180 177]
  [172 181 178]
  [173 182 179]]

 [[144 155 147]
  [143 154 146]
  [141 152 144]
  ...
  [171 180 177]
  [171 180 177]
  [171 180 177]]

 ...

 [[ 16  14  20]
  [ 17  15  21]
  [ 17  15  21]
  ...
  [ 54  59  68]
  [ 49  56  65]
  [ 48  55  64]]

 [[ 16  14  20]
  [ 16  14  20]
  [ 15  13  19]
  ...
  [ 52  57  66]
  [ 50  57  66]
  [ 50  57  66]]

 [[ 16  14  20]
  [ 15  13  19]
  [ 14  12  18]
  ...
  [ 56  61  70]
  [ 53  60  69]
  [ 52  59  68]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:09] "POST / HTTP/1.1" 200 -


24-05-31 08:52:08 - Searching [[[148 155 158]
  [147 154 157]
  [147 154 157]
  ...
  [172 186 182]
  [173 185 179]
  [172 184 178]]

 [[148 155 158]
  [148 155 158]
  [147 154 157]
  ...
  [169 183 179]
  [172 184 178]
  [172 184 178]]

 [[148 156 156]
  [148 156 156]
  [147 154 157]
  ...
  [170 181 178]
  [173 183 177]
  [175 185 179]]

 ...

 [[ 26  33  36]
  [ 27  34  37]
  [ 26  33  36]
  ...
  [134 161 171]
  [135 161 173]
  [135 162 172]]

 [[ 20  26  31]
  [ 22  28  33]
  [ 24  31  34]
  ...
  [130 158 169]
  [130 157 171]
  [128 156 167]]

 [[ 13  19  24]
  [ 17  23  28]
  [ 20  27  30]
  ...
  [125 154 168]
  [125 154 168]
  [124 153 167]]] in 34 length datastore
24-05-31 08:52:10 - Searching [[[150 158 157]
  [150 158 157]
  [151 160 157]
  ...
  [177 185 184]
  [177 186 183]
  [177 186 183]]

 [[150 158 157]
  [151 159 158]
  [151 160 157]
  ...
  [176 184 183]
  [176 185 182]
  [177 186 183]]

 [[151 160 157]
  [151 160 157]
  [152 161 158]
  ...
  [176 184 183]
  [177 18

INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:10] "POST / HTTP/1.1" 200 -


24-05-31 08:52:10 - find function duration 0.3067312240600586 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:11] "POST / HTTP/1.1" 200 -


24-05-31 08:52:11 - Searching [[[153 160 163]
  [153 160 163]
  [149 158 161]
  ...
  [174 184 184]
  [173 184 182]
  [172 183 181]]

 [[153 160 163]
  [152 159 162]
  [150 159 162]
  ...
  [174 184 184]
  [174 185 183]
  [174 185 183]]

 [[152 159 162]
  [152 159 162]
  [150 159 162]
  ...
  [172 182 182]
  [175 183 183]
  [176 184 184]]

 ...

 [[ 57  67  74]
  [ 52  62  69]
  [ 48  59  63]
  ...
  [ 68  77  97]
  [ 61  72  94]
  [ 59  70  92]]

 [[ 61  69  76]
  [ 51  59  66]
  [ 43  52  56]
  ...
  [ 64  73  93]
  [ 59  68  88]
  [ 59  68  88]]

 [[ 67  75  82]
  [ 53  61  68]
  [ 41  50  54]
  ...
  [ 62  71  91]
  [ 60  69  89]
  [ 61  70  90]]] in 34 length datastore
24-05-31 08:52:12 - Searching [[[146 159 161]
  [145 158 160]
  [144 158 157]
  ...
  [166 178 184]
  [163 177 183]
  [163 177 183]]

 [[146 159 161]
  [145 158 160]
  [144 158 157]
  ...
  [167 179 185]
  [167 179 185]
  [165 179 185]]

 [[148 160 160]
  [147 159 159]
  [145 157 157]
  ...
  [169 181 187]
  [169 18

INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:12] "POST / HTTP/1.1" 200 -


24-05-31 08:52:12 - find function duration 0.5177733898162842 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:13] "POST / HTTP/1.1" 200 -


24-05-31 08:52:13 - Searching [[[155 161 156]
  [155 161 156]
  [154 160 155]
  ...
  [174 182 182]
  [176 181 182]
  [176 181 182]]

 [[154 160 155]
  [154 160 155]
  [154 160 155]
  ...
  [174 182 182]
  [176 181 182]
  [176 181 182]]

 [[153 160 157]
  [153 160 157]
  [154 161 158]
  ...
  [174 181 184]
  [174 182 182]
  [174 182 182]]

 ...

 [[201 209 208]
  [199 207 206]
  [199 208 205]
  ...
  [ 67  70  85]
  [ 74  77  92]
  [ 82  85 100]]

 [[200 208 207]
  [199 207 206]
  [200 209 206]
  ...
  [ 72  75  89]
  [ 86  87 101]
  [ 98  99 113]]

 [[200 208 207]
  [199 207 206]
  [200 209 206]
  ...
  [ 78  81  95]
  [ 90  91 105]
  [100 101 115]]] in 34 length datastore
24-05-31 08:52:14 - Searching [[[161 168 165]
  [160 167 164]
  [159 166 163]
  ...
  [183 188 197]
  [183 187 198]
  [184 188 199]]

 [[161 168 165]
  [161 168 165]
  [160 167 164]
  ...
  [183 188 197]
  [183 187 198]
  [184 188 199]]

 [[161 168 165]
  [161 168 165]
  [161 168 165]
  ...
  [183 188 197]
  [183 18

INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:14] "POST / HTTP/1.1" 200 -


24-05-31 08:52:14 - find function duration 0.32946252822875977 seconds
24-05-31 08:52:15 - Searching [[[161 169 168]
  [158 166 165]
  [156 164 163]
  ...
  [185 190 199]
  [184 189 198]
  [184 189 198]]

 [[161 169 168]
  [160 168 167]
  [159 167 166]
  ...
  [185 190 199]
  [185 190 199]
  [185 190 199]]

 [[161 169 168]
  [162 170 169]
  [162 171 168]
  ...
  [184 191 200]
  [184 191 200]
  [184 191 200]]

 ...

 [[213 221 220]
  [213 221 220]
  [212 221 218]
  ...
  [101 121 139]
  [104 122 139]
  [106 124 141]]

 [[212 220 219]
  [212 220 219]
  [212 220 219]
  ...
  [ 99 116 135]
  [103 119 136]
  [104 120 137]]

 [[211 219 218]
  [212 220 219]
  [211 219 218]
  ...
  [ 98 115 134]
  [103 119 136]
  [105 121 138]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:15] "POST / HTTP/1.1" 200 -


24-05-31 08:52:15 - find function duration 0.32741284370422363 seconds
24-05-31 08:52:16 - Searching [[[160 172 178]
  [159 171 177]
  [158 170 176]
  ...
  [183 194 198]
  [185 194 198]
  [185 194 198]]

 [[159 171 177]
  [158 170 176]
  [158 170 176]
  ...
  [183 194 198]
  [185 194 198]
  [185 194 198]]

 [[160 170 177]
  [160 170 177]
  [160 171 175]
  ...
  [185 194 198]
  [185 194 198]
  [185 194 198]]

 ...

 [[ 82 104 116]
  [ 84 106 118]
  [ 84 106 118]
  ...
  [108 122 145]
  [108 124 147]
  [110 126 149]]

 [[ 76 101 111]
  [ 80 105 115]
  [ 81 105 117]
  ...
  [109 125 148]
  [111 126 152]
  [112 127 153]]

 [[ 73 101 108]
  [ 75 103 110]
  [ 78 102 114]
  ...
  [108 124 147]
  [108 123 149]
  [108 123 149]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:16] "POST / HTTP/1.1" 200 -


24-05-31 08:52:16 - find function duration 0.43153810501098633 seconds
24-05-31 08:52:17 - Searching [[[167 176 166]
  [166 175 165]
  [163 174 164]
  ...
  [187 196 199]
  [186 195 198]
  [186 195 198]]

 [[167 176 166]
  [166 175 165]
  [164 175 165]
  ...
  [186 195 198]
  [185 194 197]
  [185 194 197]]

 [[167 176 166]
  [167 176 166]
  [167 175 168]
  ...
  [187 194 197]
  [187 194 197]
  [186 193 196]]

 ...

 [[102 119 132]
  [103 120 133]
  [105 121 133]
  ...
  [ 83  95 107]
  [ 79  89  99]
  [ 79  89  99]]

 [[105 124 137]
  [106 125 138]
  [111 129 140]
  ...
  [ 94 106 118]
  [ 86  98 108]
  [ 77  89  99]]

 [[106 125 138]
  [111 130 143]
  [117 135 146]
  ...
  [102 114 126]
  [ 95 107 117]
  [ 81  93 103]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:17] "POST / HTTP/1.1" 200 -


24-05-31 08:52:17 - find function duration 0.49362611770629883 seconds
24-05-31 08:52:18 - Searching [[[169 180 164]
  [169 180 164]
  [167 180 166]
  ...
  [190 199 202]
  [190 199 202]
  [190 199 202]]

 [[170 181 165]
  [171 182 166]
  [169 182 168]
  ...
  [191 200 203]
  [191 200 203]
  [191 200 203]]

 [[171 181 168]
  [171 181 168]
  [172 182 170]
  ...
  [193 199 204]
  [193 199 204]
  [193 199 204]]

 ...

 [[216 230 229]
  [214 228 227]
  [212 226 225]
  ...
  [ 89  92 106]
  [ 92  95 109]
  [ 94  97 111]]

 [[213 229 228]
  [211 227 226]
  [211 225 224]
  ...
  [ 86  89 103]
  [ 88  92 103]
  [ 90  94 105]]

 [[214 230 229]
  [211 227 226]
  [210 224 223]
  ...
  [ 88  91 105]
  [ 92  96 107]
  [ 93  97 108]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:18] "POST / HTTP/1.1" 200 -


24-05-31 08:52:18 - find function duration 0.3235900402069092 seconds
24-05-31 08:52:19 - Searching [[[178 189 181]
  [177 188 180]
  [178 189 181]
  ...
  [200 209 213]
  [199 207 214]
  [198 206 213]]

 [[179 190 182]
  [178 189 181]
  [178 189 181]
  ...
  [200 209 213]
  [199 207 214]
  [198 206 213]]

 [[180 191 183]
  [179 190 182]
  [178 189 181]
  ...
  [199 208 212]
  [199 207 214]
  [199 207 214]]

 ...

 [[231 242 232]
  [229 240 230]
  [223 234 224]
  ...
  [125 143 160]
  [127 145 162]
  [128 146 163]]

 [[228 242 231]
  [226 240 229]
  [223 234 224]
  ...
  [122 139 158]
  [123 140 159]
  [125 142 161]]

 [[227 241 230]
  [225 239 228]
  [222 233 223]
  ...
  [120 137 156]
  [122 139 158]
  [125 142 161]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:19] "POST / HTTP/1.1" 200 -


24-05-31 08:52:19 - find function duration 0.32481980323791504 seconds
24-05-31 08:52:20 - Searching [[[189 195 194]
  [188 194 193]
  [186 192 191]
  ...
  [213 220 223]
  [211 220 223]
  [210 219 222]]

 [[189 195 194]
  [188 194 193]
  [187 193 192]
  ...
  [212 219 222]
  [210 219 222]
  [211 220 223]]

 [[189 195 194]
  [189 195 194]
  [189 196 193]
  ...
  [211 218 221]
  [210 219 222]
  [211 220 223]]

 ...

 [[246 253 246]
  [245 252 245]
  [241 249 242]
  ...
  [126 148 173]
  [127 149 174]
  [127 149 174]]

 [[247 254 247]
  [244 251 244]
  [240 248 241]
  ...
  [123 145 170]
  [124 146 171]
  [124 146 171]]

 [[247 254 247]
  [242 250 243]
  [239 247 240]
  ...
  [120 142 167]
  [121 143 168]
  [122 144 169]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:20] "POST / HTTP/1.1" 200 -


24-05-31 08:52:20 - find function duration 0.318526029586792 seconds
24-05-31 08:52:21 - Searching [[[189 197 197]
  [189 197 197]
  [189 197 197]
  ...
  [212 219 222]
  [212 219 222]
  [213 220 223]]

 [[189 197 197]
  [189 197 197]
  [189 197 197]
  ...
  [212 219 222]
  [212 219 222]
  [213 220 223]]

 [[188 196 195]
  [188 196 195]
  [188 196 195]
  ...
  [212 219 222]
  [212 219 222]
  [213 220 223]]

 ...

 [[138 160 172]
  [136 158 170]
  [134 155 170]
  ...
  [127 150 172]
  [129 152 174]
  [131 154 176]]

 [[140 159 172]
  [138 157 170]
  [135 156 171]
  ...
  [127 150 172]
  [128 151 173]
  [131 154 176]]

 [[140 159 172]
  [138 157 170]
  [135 156 171]
  ...
  [125 148 170]
  [127 150 172]
  [130 153 175]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:21] "POST / HTTP/1.1" 200 -


24-05-31 08:52:21 - find function duration 0.32161569595336914 seconds
24-05-31 08:52:22 - Searching [[[184 201 197]
  [184 201 197]
  [184 201 197]
  ...
  [209 223 229]
  [208 222 228]
  [209 223 229]]

 [[184 201 197]
  [184 201 197]
  [184 201 197]
  ...
  [208 222 228]
  [208 222 228]
  [210 224 230]]

 [[186 201 197]
  [186 201 197]
  [186 201 197]
  ...
  [209 221 227]
  [208 222 228]
  [211 225 231]]

 ...

 [[238 251 249]
  [236 250 248]
  [230 244 243]
  ...
  [ 89 116 153]
  [ 91 118 155]
  [ 93 120 157]]

 [[238 252 248]
  [238 252 250]
  [232 246 245]
  ...
  [ 88 114 150]
  [ 89 115 152]
  [ 90 116 153]]

 [[236 250 246]
  [236 251 247]
  [231 245 244]
  ...
  [ 89 115 151]
  [ 90 113 151]
  [ 91 114 152]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:22] "POST / HTTP/1.1" 200 -


24-05-31 08:52:22 - find function duration 0.3116140365600586 seconds
24-05-31 08:52:23 - Searching [[[192 200 199]
  [192 200 199]
  [192 200 199]
  ...
  [210 223 225]
  [212 224 226]
  [212 224 226]]

 [[192 200 199]
  [192 200 199]
  [192 200 199]
  ...
  [210 223 225]
  [211 223 225]
  [212 224 226]]

 [[192 200 199]
  [192 200 199]
  [192 200 199]
  ...
  [211 222 226]
  [211 222 226]
  [211 222 226]]

 ...

 [[156 169 171]
  [144 159 162]
  [133 149 155]
  ...
  [113 152 180]
  [113 152 180]
  [112 151 179]]

 [[148 163 166]
  [140 155 158]
  [132 148 154]
  ...
  [116 152 182]
  [115 151 181]
  [114 150 180]]

 [[140 155 158]
  [139 156 159]
  [136 152 158]
  ...
  [116 152 182]
  [114 150 180]
  [113 149 179]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:23] "POST / HTTP/1.1" 200 -


24-05-31 08:52:23 - find function duration 0.4350309371948242 seconds
24-05-31 08:52:24 - Searching [[[186 200 199]
  [187 201 200]
  [187 201 199]
  ...
  [212 224 230]
  [212 224 230]
  [212 224 230]]

 [[186 200 199]
  [187 201 200]
  [187 201 199]
  ...
  [210 222 228]
  [210 222 228]
  [210 222 228]]

 [[186 200 199]
  [186 200 199]
  [187 201 199]
  ...
  [210 222 228]
  [210 222 228]
  [210 222 228]]

 ...

 [[ 88 113 145]
  [ 90 116 146]
  [ 88 116 146]
  ...
  [ 98 135 157]
  [ 99 136 158]
  [ 99 136 158]]

 [[ 86 111 145]
  [ 88 113 145]
  [ 85 113 144]
  ...
  [101 136 156]
  [101 136 156]
  [102 137 157]]

 [[ 86 111 145]
  [ 86 111 145]
  [ 82 110 141]
  ...
  [101 136 156]
  [102 137 157]
  [103 138 158]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:24] "POST / HTTP/1.1" 200 -


24-05-31 08:52:24 - find function duration 0.45383548736572266 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:25] "POST / HTTP/1.1" 200 -


24-05-31 08:52:25 - Searching [[[192 203 200]
  [191 202 199]
  [191 202 200]
  ...
  [212 222 229]
  [214 222 229]
  [214 222 229]]

 [[192 203 200]
  [191 202 199]
  [190 201 199]
  ...
  [212 222 229]
  [214 222 229]
  [214 222 229]]

 [[191 202 200]
  [191 202 200]
  [190 201 199]
  ...
  [212 222 229]
  [214 222 229]
  [214 222 229]]

 ...

 [[ 65  69  74]
  [ 62  66  71]
  [ 60  66  71]
  ...
  [224 247 255]
  [224 247 255]
  [224 247 255]]

 [[ 62  67  70]
  [ 62  67  70]
  [ 66  71  74]
  ...
  [228 250 255]
  [228 249 255]
  [227 248 255]]

 [[ 58  63  64]
  [ 61  66  67]
  [ 69  74  77]
  ...
  [231 250 255]
  [229 250 255]
  [228 249 255]]] in 34 length datastore
24-05-31 08:52:26 - Searching [[[112 127 136]
  [116 131 140]
  [120 135 144]
  ...
  [192 205 203]
  [191 204 202]
  [191 204 202]]

 [[111 126 135]
  [112 127 136]
  [112 127 136]
  ...
  [192 205 203]
  [192 205 203]
  [192 205 203]]

 [[116 131 140]
  [114 129 138]
  [110 127 136]
  ...
  [194 205 203]
  [192 20

INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:26] "POST / HTTP/1.1" 200 -


24-05-31 08:52:26 - find function duration 0.3747565746307373 seconds
24-05-31 08:52:27 - Searching [[[104 112 119]
  [104 112 119]
  [105 114 118]
  ...
  [175 189 185]
  [175 189 185]
  [176 190 186]]

 [[101 109 116]
  [101 109 116]
  [102 111 115]
  ...
  [176 190 186]
  [177 191 187]
  [177 191 187]]

 [[102 108 115]
  [103 109 116]
  [103 109 114]
  ...
  [176 190 186]
  [177 191 187]
  [178 192 188]]

 ...

 [[113 127 116]
  [122 136 125]
  [128 141 133]
  ...
  [242 206 146]
  [244 208 148]
  [246 210 150]]

 [[118 129 121]
  [124 137 129]
  [127 139 133]
  ...
  [240 207 144]
  [241 208 145]
  [242 209 146]]

 [[119 130 122]
  [126 137 129]
  [127 139 133]
  ...
  [238 206 141]
  [238 205 142]
  [239 206 143]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:27] "POST / HTTP/1.1" 200 -


24-05-31 08:52:27 - find function duration 0.3910665512084961 seconds
24-05-31 08:52:28 - Searching [[[100  96  95]
  [ 98  94  93]
  [ 94  91  87]
  ...
  [182 188 193]
  [182 188 193]
  [182 188 193]]

 [[ 96  92  91]
  [ 95  91  90]
  [ 94  91  87]
  ...
  [181 187 192]
  [181 187 192]
  [181 187 192]]

 [[ 94  92  91]
  [ 91  89  88]
  [ 88  87  83]
  ...
  [181 188 191]
  [181 188 191]
  [181 188 191]]

 ...

 [[106 100  87]
  [106 100  87]
  [104 101  87]
  ...
  [234 194 112]
  [234 194 111]
  [234 194 111]]

 [[106 100  87]
  [105  99  86]
  [104  98  87]
  ...
  [234 194 112]
  [235 195 112]
  [236 196 113]]

 [[107 101  88]
  [105  99  86]
  [104  98  87]
  ...
  [235 195 113]
  [236 196 113]
  [237 197 114]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:28] "POST / HTTP/1.1" 200 -


24-05-31 08:52:28 - find function duration 0.3861978054046631 seconds
24-05-31 08:52:29 - Searching [[[ 86  74  72]
  [ 89  77  75]
  [ 87  78  74]
  ...
  [180 189 192]
  [180 189 192]
  [180 189 192]]

 [[ 89  77  75]
  [ 90  81  78]
  [ 91  82  78]
  ...
  [180 189 192]
  [180 189 192]
  [180 189 192]]

 [[ 87  78  74]
  [ 90  81  77]
  [ 91  82  78]
  ...
  [179 188 191]
  [180 190 190]
  [180 190 190]]

 ...

 [[103 107  95]
  [104 108  96]
  [105 109  97]
  ...
  [239 197 114]
  [237 195 112]
  [237 195 112]]

 [[103 110  97]
  [102 109  96]
  [103 108  93]
  ...
  [237 197 115]
  [237 197 115]
  [237 197 115]]

 [[106 113 100]
  [103 110  97]
  [102 107  92]
  ...
  [238 198 116]
  [239 199 117]
  [240 200 118]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:29] "POST / HTTP/1.1" 200 -


24-05-31 08:52:29 - find function duration 0.4038839340209961 seconds
24-05-31 08:52:30 - Searching [[[255 254 246]
  [255 253 245]
  [255 252 244]
  ...
  [176 189 187]
  [176 188 188]
  [177 189 189]]

 [[255 253 245]
  [255 253 245]
  [255 254 246]
  ...
  [176 189 187]
  [177 189 189]
  [177 189 189]]

 [[251 248 240]
  [254 251 243]
  [255 254 246]
  ...
  [177 189 189]
  [177 189 191]
  [177 189 191]]

 ...

 [[213 240 244]
  [202 227 229]
  [202 226 224]
  ...
  [246 200 122]
  [247 201 123]
  [248 202 124]]

 [[213 240 244]
  [199 224 226]
  [196 220 220]
  ...
  [244 201 122]
  [246 203 124]
  [247 204 125]]

 [[207 234 238]
  [209 234 236]
  [200 224 224]
  ...
  [241 198 119]
  [242 199 120]
  [244 201 122]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:30] "POST / HTTP/1.1" 200 -


24-05-31 08:52:30 - find function duration 0.4007735252380371 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:31] "POST / HTTP/1.1" 200 -


24-05-31 08:52:31 - Searching [[[255 255 250]
  [255 255 250]
  [255 255 250]
  ...
  [176 192 191]
  [177 193 192]
  [177 193 192]]

 [[255 255 250]
  [255 255 250]
  [255 255 249]
  ...
  [175 191 190]
  [176 192 191]
  [176 192 191]]

 [[255 255 249]
  [255 255 249]
  [255 255 249]
  ...
  [174 190 189]
  [176 190 189]
  [177 191 190]]

 ...

 [[ 65  97 126]
  [ 64  96 125]
  [ 60  94 123]
  ...
  [ 72 102 129]
  [ 70 103 129]
  [ 70 103 129]]

 [[ 59  96 122]
  [ 59  96 122]
  [ 58  95 121]
  ...
  [ 72 105 131]
  [ 71 105 129]
  [ 69 105 129]]

 [[ 55  95 120]
  [ 56  96 121]
  [ 56  96 121]
  ...
  [ 74 107 133]
  [ 70 106 130]
  [ 69 105 129]]] in 34 length datastore
24-05-31 08:52:32 - Searching [[[255 255 251]
  [253 255 249]
  [254 254 248]
  ...
  [170 189 186]
  [170 191 188]
  [172 193 190]]

 [[254 255 250]
  [254 255 250]
  [255 255 249]
  ...
  [170 189 186]
  [172 191 188]
  [172 193 190]]

 [[253 254 245]
  [254 255 246]
  [255 255 249]
  ...
  [171 190 187]
  [172 19

INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:32] "POST / HTTP/1.1" 200 -


24-05-31 08:52:32 - find function duration 0.3866417407989502 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:33] "POST / HTTP/1.1" 200 -


24-05-31 08:52:33 - Searching [[[254 251 246]
  [254 251 246]
  [255 252 247]
  ...
  [178 188 188]
  [182 190 190]
  [182 190 190]]

 [[255 254 249]
  [255 253 248]
  [255 252 247]
  ...
  [178 188 188]
  [181 189 189]
  [182 190 190]]

 [[251 247 242]
  [253 249 244]
  [255 252 244]
  ...
  [176 188 188]
  [178 188 188]
  [179 189 189]]

 ...

 [[207 225 218]
  [214 230 223]
  [212 225 217]
  ...
  [247 203 120]
  [246 202 119]
  [246 202 119]]

 [[205 225 220]
  [212 230 223]
  [204 219 211]
  ...
  [246 202 118]
  [246 202 118]
  [247 203 119]]

 [[206 226 221]
  [214 232 225]
  [201 216 208]
  ...
  [246 202 118]
  [247 203 119]
  [248 204 120]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:34] "POST / HTTP/1.1" 200 -


24-05-31 08:52:34 - Searching [[[255 255 243]
  [255 255 243]
  [255 255 243]
  ...
  [178 192 188]
  [177 191 187]
  [177 191 187]]

 [[255 255 245]
  [255 255 244]
  [254 254 242]
  ...
  [178 192 188]
  [178 192 188]
  [178 192 188]]

 [[251 249 238]
  [253 251 240]
  [255 253 242]
  ...
  [180 191 189]
  [180 191 189]
  [180 191 189]]

 ...

 [[215 235 240]
  [221 242 240]
  [219 236 225]
  ...
  [243 199 116]
  [246 200 116]
  [247 201 117]]

 [[217 235 242]
  [221 239 240]
  [213 230 221]
  ...
  [244 200 117]
  [246 200 116]
  [245 200 113]]

 [[217 235 242]
  [220 238 239]
  [215 231 224]
  ...
  [246 202 118]
  [247 201 117]
  [245 200 113]]] in 34 length datastore
24-05-31 08:52:35 - Searching [[[255 251 244]
  [255 251 244]
  [255 252 245]
  ...
  [170 182 184]
  [170 181 185]
  [170 181 185]]

 [[255 249 242]
  [255 250 243]
  [255 249 242]
  ...
  [171 183 185]
  [171 182 186]
  [170 181 185]]

 [[245 240 231]
  [249 244 235]
  [254 249 240]
  ...
  [172 184 186]
  [171 18

INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:35] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:36] "POST / HTTP/1.1" 200 -


24-05-31 08:52:36 - Searching [[[255 248 239]
  [252 245 236]
  [252 246 235]
  ...
  [174 183 186]
  [173 185 187]
  [173 185 187]]

 [[255 250 241]
  [255 248 239]
  [254 248 237]
  ...
  [173 182 185]
  [171 183 185]
  [171 183 185]]

 [[248 241 232]
  [250 243 234]
  [253 247 236]
  ...
  [172 181 184]
  [172 181 184]
  [172 181 184]]

 ...

 [[209 232 240]
  [210 233 241]
  [207 233 240]
  ...
  [234 193 120]
  [233 192 119]
  [231 192 118]]

 [[207 233 240]
  [208 234 241]
  [207 232 242]
  ...
  [234 194 122]
  [234 194 122]
  [232 194 122]]

 [[207 233 240]
  [208 234 241]
  [206 231 241]
  ...
  [234 194 122]
  [232 193 124]
  [231 192 123]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:37] "POST / HTTP/1.1" 200 -


24-05-31 08:52:37 - Searching [[[255 253 238]
  [255 252 237]
  [252 251 237]
  ...
  [168 183 186]
  [168 182 188]
  [168 182 188]]

 [[255 255 241]
  [255 254 239]
  [253 252 238]
  ...
  [168 183 186]
  [168 182 188]
  [168 182 188]]

 [[249 246 232]
  [251 248 234]
  [254 250 239]
  ...
  [170 182 186]
  [170 182 188]
  [170 182 188]]

 ...

 [[ 69  99 118]
  [ 64  94 113]
  [ 61  91 110]
  ...
  [236 196 121]
  [236 195 122]
  [236 195 122]]

 [[ 65  96 117]
  [ 65  96 117]
  [ 62  93 114]
  ...
  [237 196 123]
  [236 197 123]
  [236 196 124]]

 [[ 62  95 115]
  [ 68 101 121]
  [ 67  98 119]
  ...
  [238 197 124]
  [237 197 125]
  [237 197 125]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:38] "POST / HTTP/1.1" 200 -


24-05-31 08:52:38 - Searching [[[253 246 231]
  [254 247 232]
  [255 248 233]
  ...
  [174 183 180]
  [176 181 179]
  [177 182 180]]

 [[255 250 235]
  [255 250 235]
  [255 249 234]
  ...
  [173 182 179]
  [175 182 179]
  [177 182 180]]

 [[251 242 228]
  [253 244 230]
  [255 247 234]
  ...
  [173 182 179]
  [175 182 179]
  [176 183 180]]

 ...

 [[179 192 194]
  [177 190 192]
  [175 188 190]
  ...
  [171 174 172]
  [171 173 173]
  [172 174 174]]

 [[178 191 193]
  [177 190 192]
  [175 188 190]
  ...
  [172 175 173]
  [171 174 172]
  [170 173 171]]

 [[177 190 192]
  [176 189 191]
  [175 188 190]
  ...
  [173 176 174]
  [171 174 172]
  [169 172 170]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:39] "POST / HTTP/1.1" 200 -


24-05-31 08:52:39 - Searching [[[174 181 168]
  [175 182 169]
  [173 182 169]
  ...
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 [[174 181 168]
  [175 182 169]
  [173 182 169]
  ...
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 [[174 181 168]
  [175 182 169]
  [175 182 169]
  ...
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 ...

 [[ 94 115 130]
  [ 94 115 130]
  [ 93 114 129]
  ...
  [154 181 191]
  [146 181 191]
  [143 181 193]]

 [[ 95 117 129]
  [ 95 117 129]
  [ 95 117 129]
  ...
  [156 181 191]
  [149 181 192]
  [146 181 194]]

 [[ 94 116 127]
  [ 96 118 129]
  [ 96 118 130]
  ...
  [159 184 194]
  [150 182 195]
  [145 180 193]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:40] "POST / HTTP/1.1" 200 -


24-05-31 08:52:40 - Searching [[[132 133 129]
  [132 133 129]
  [133 134 130]
  ...
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 [[136 137 133]
  [135 136 132]
  [135 136 132]
  ...
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 [[137 138 134]
  [136 137 133]
  [133 137 132]
  ...
  [255 254 253]
  [255 254 253]
  [255 254 253]]

 ...

 [[221 225 213]
  [220 224 212]
  [221 226 211]
  ...
  [187 195 185]
  [187 195 185]
  [188 196 186]]

 [[219 223 211]
  [219 223 211]
  [220 225 210]
  ...
  [188 196 186]
  [189 197 187]
  [190 198 188]]

 [[218 222 210]
  [219 223 211]
  [221 226 211]
  ...
  [188 196 186]
  [189 197 187]
  [190 198 188]]] in 34 length datastore
24-05-31 08:52:41 - Searching [[[105 120 129]
  [106 121 130]
  [107 122 131]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 [[107 122 131]
  [107 122 131]
  [106 121 130]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 [[110 123 131]
  [109 122 130]
  [108 121 129]
  ...
  [255 255 255]
  [255 25

INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:41] "POST / HTTP/1.1" 200 -


24-05-31 08:52:41 - find function duration 0.31569433212280273 seconds


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:42] "POST / HTTP/1.1" 200 -


24-05-31 08:52:42 - Searching [[[116 129 121]
  [114 127 119]
  [112 125 117]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 [[115 128 120]
  [114 127 119]
  [113 126 118]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 [[113 125 119]
  [113 125 119]
  [114 127 119]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 ...

 [[136 150 139]
  [136 150 139]
  [136 150 139]
  ...
  [116 130 126]
  [116 130 126]
  [114 128 124]]

 [[135 149 138]
  [136 150 139]
  [136 150 139]
  ...
  [118 132 128]
  [119 133 127]
  [117 131 125]]

 [[134 148 137]
  [135 149 138]
  [135 149 138]
  ...
  [119 133 129]
  [119 133 127]
  [117 131 125]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:43] "POST / HTTP/1.1" 200 -


24-05-31 08:52:43 - Searching [[[114 126 126]
  [113 125 125]
  [113 125 125]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 [[112 124 124]
  [112 124 124]
  [112 124 124]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 [[115 127 127]
  [115 127 127]
  [114 126 126]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 ...

 [[140 151 148]
  [141 152 149]
  [141 152 149]
  ...
  [115 129 128]
  [113 127 126]
  [113 127 126]]

 [[136 150 146]
  [137 151 147]
  [140 151 148]
  ...
  [117 131 129]
  [116 130 128]
  [116 130 128]]

 [[136 150 146]
  [137 151 147]
  [140 151 148]
  ...
  [118 132 130]
  [118 132 130]
  [119 133 131]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:44] "POST / HTTP/1.1" 200 -


24-05-31 08:52:44 - Searching [[[122 139 130]
  [119 136 127]
  [118 135 126]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 [[121 138 129]
  [120 137 128]
  [119 136 127]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 [[120 135 127]
  [120 135 127]
  [121 136 128]
  ...
  [255 255 255]
  [255 255 255]
  [254 254 254]]

 ...

 [[143 155 149]
  [144 156 150]
  [144 157 149]
  ...
  [121 134 136]
  [122 133 137]
  [123 134 138]]

 [[143 155 149]
  [144 156 150]
  [144 157 149]
  ...
  [123 136 138]
  [123 134 138]
  [123 134 138]]

 [[144 156 150]
  [144 156 150]
  [144 157 149]
  ...
  [126 139 141]
  [126 137 141]
  [125 136 140]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:45] "POST / HTTP/1.1" 200 -


24-05-31 08:52:45 - Searching [[[129 143 139]
  [129 143 139]
  [129 143 137]
  ...
  [255 255 255]
  [255 254 255]
  [255 254 255]]

 [[129 143 139]
  [129 143 139]
  [129 143 137]
  ...
  [255 255 255]
  [255 254 255]
  [255 254 255]]

 [[129 143 139]
  [129 143 139]
  [128 142 136]
  ...
  [255 255 255]
  [255 254 255]
  [255 254 255]]

 ...

 [[155 166 158]
  [155 166 158]
  [154 165 155]
  ...
  [131 145 143]
  [132 146 142]
  [132 146 142]]

 [[154 167 159]
  [153 166 158]
  [153 167 156]
  ...
  [135 149 145]
  [134 148 144]
  [133 147 143]]

 [[153 166 158]
  [152 165 157]
  [151 165 154]
  ...
  [134 148 144]
  [132 146 142]
  [130 144 140]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:46] "POST / HTTP/1.1" 200 -


24-05-31 08:52:46 - Searching [[[129 143 137]
  [127 141 135]
  [126 140 134]
  ...
  [255 254 255]
  [253 255 254]
  [252 255 251]]

 [[128 142 136]
  [127 141 135]
  [126 140 134]
  ...
  [255 254 255]
  [253 255 254]
  [252 255 251]]

 [[127 141 135]
  [128 142 136]
  [127 141 135]
  ...
  [255 255 255]
  [253 255 254]
  [252 255 251]]

 ...

 [[183 204 195]
  [181 202 193]
  [184 203 194]
  ...
  [198 209 206]
  [196 207 204]
  [195 206 203]]

 [[184 205 196]
  [180 201 192]
  [181 203 191]
  ...
  [199 210 207]
  [197 208 205]
  [196 207 204]]

 [[187 208 199]
  [180 201 192]
  [180 202 190]
  ...
  [200 211 208]
  [198 209 206]
  [198 209 206]]] in 34 length datastore


INFO:werkzeug:127.0.0.1 - - [31/May/2024 08:52:47] "POST / HTTP/1.1" 200 -


24-05-31 08:52:47 - Searching [[[137 143 142]
  [137 143 142]
  [135 144 141]
  ...
  [254 255 253]
  [254 255 253]
  [254 255 253]]

 [[137 143 142]
  [137 143 142]
  [135 144 141]
  ...
  [254 255 253]
  [254 255 253]
  [254 255 253]]

 [[135 144 141]
  [135 144 141]
  [135 144 141]
  ...
  [255 255 254]
  [254 255 253]
  [254 255 253]]

 ...

 [[194 207 205]
  [191 204 202]
  [189 203 199]
  ...
  [202 211 208]
  [202 211 208]
  [201 210 207]]

 [[195 208 206]
  [190 203 201]
  [188 199 196]
  ...
  [202 210 209]
  [202 210 209]
  [202 210 209]]

 [[195 208 206]
  [189 202 200]
  [186 197 194]
  ...
  [202 210 209]
  [202 210 209]
  [202 210 209]]] in 34 length datastore
