<a href="https://colab.research.google.com/github/nilu-ai/Restaurant_Fttx_project/blob/main/pre%20trained%20facenet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install deepface

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.3/97.3 kB 3.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 62.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.4/88.4 kB 10.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 9.5 MB/s eta 0:00:00
  Created wheel for fire: filename=fire-0.6.0-py2.py3-none-any.whl size=117029 sha256=0241437da2ef6f979dc73c7215cd75f5203642a185ae57a56b368ac9a23e7f8a
  Stored in directory: /root/.cache/pip/wheels/d6/6d/5d/5b73fa0f46d01a793713f8859201361e9e581ced8c75e5c6a3
Successfully built fire


In [1]:
!unzip trainss

Archive:  trainss.zip
   creating: trainss/abhi/
  inflating: trainss/abhi/WIN_20240524_15_28_37_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_39_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_41_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_42_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_44_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_45_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_47_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_48_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_50_Pro.jpg  
  inflating: trainss/abhi/WIN_20240524_15_28_52_Pro.jpg  
   creating: trainss/Abhishek 1/
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_24_Pro (2).jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_24_Pro.jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_25_Pro (2).jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_28_25_Pro.jpg  
  inflating: trainss/Abhishek 1/WIN_20240524_15_29_22_Pro.jpg  
  inflatin

In [33]:
from deepface import DeepFace
predictions = DeepFace.find(img_path = "/content/trainss/Rohan/WIN_20240524_15_21_36_Pro.jpg", db_path = "/content/trainss",model_name="Facenet512")
# print(df)
# if df[0].distance.empty:
#   print("Unkonw")
# elif df[0].distance[0]<0.3:
#   print(df)
# else:
#   print("Unknow User")
import re

if not predictions[0].empty and predictions[0].distance[0] < 0.3:
  data=predictions[0].to_dict()
  print(data)
  response = {
                    'status': 'success',
                    'data': data["identity"][0].split("/")[3]

                }
else:
 response = {
                    'status': 'unknown User'
                }

print(response)


24-06-04 06:32:17 - Searching /content/trainss/Rohan/WIN_20240524_15_21_36_Pro.jpg in 36 length datastore
24-06-04 06:32:18 - find function duration 0.9366366863250732 seconds
{'identity': {0: '/content/trainss/Rohan/WIN_20240524_15_21_36_Pro.jpg'}, 'hash': {0: 'ee721f76c0af38081115b527cfb49d84f9f4ca32'}, 'target_x': {0: 536}, 'target_y': {0: 282}, 'target_w': {0: 270}, 'target_h': {0: 270}, 'source_x': {0: 536}, 'source_y': {0: 282}, 'source_w': {0: 270}, 'source_h': {0: 270}, 'threshold': {0: 0.3}, 'distance': {0: 0.0}}
{'status': 'success', 'data': 'Rohan'}


In [34]:
from flask import Flask, request, jsonify
import cv2
import numpy as np
import base64
from deepface import DeepFace
import os
app = Flask(__name__)
from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(5000)"))
@app.route('/', methods=['GET', 'POST'])
def upload_image():
    if request.method == 'POST':
        data = request.json
        img_data = data['image'].split(',')[1]
        nparr = np.frombuffer(base64.b64decode(img_data), np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

        try:

            predictions = DeepFace.find(img_path=img, db_path="/content/trainss", model_name="Facenet512")

            if not predictions[0].empty and predictions[0].distance[0] < 0.3:
                data=predictions[0].to_dict()
                response = {
                    'status': 'success',
                    #'data': predictions[0].to_dict(),
                    'prediction':data["identity"][0].split("/")[3]
                }
            else:
                response = {
                    'status': 'unknown User'
                }
        except Exception as e:
            response = {
                'status': 'error',
                'message': str(e)
            }

        return jsonify(response)

    return """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <video id="video" width="640" height="480" autoplay></video>
        <canvas id="canvas" width="640" height="480" style="display:none;"></canvas>
        <div id="prediction"></div>
        <script>
            const video = document.getElementById('video');
            const canvas = document.getElementById('canvas');
            const predictionDiv = document.getElementById('prediction');

            async function initCamera() {
                try {
                    const stream = await navigator.mediaDevices.getUserMedia({ video: true });
                    video.srcObject = stream;
                } catch (err) {
                    console.error('Error accessing camera:', err);
                }
            }

            async function captureAndPredict() {
                const context = canvas.getContext('2d');
                context.drawImage(video, 0, 0, canvas.width, canvas.height);
                const imageData = canvas.toDataURL('image/jpeg');
                const response = await fetch('/', {
                    method: 'POST',
                    body: JSON.stringify({ image: imageData }),
                    headers: {
                        'Content-Type': 'application/json'
                    }
                });
                const result = await response.json();
                predictionDiv.innerHTML = JSON.stringify(result, null, 2);
            }

            setInterval(captureAndPredict, 1000);

            initCamera();
        </script>
    </body>
    </html>
    """


@app.route('/new_user', methods=['GET', 'POST'])
def newuser():
    if request.method == 'POST':
        data = request.get_json()
        username = data['username']
        photos = data['photos']

        # Create directory for the new user
        user_dir = os.path.join('trainss', username)
        os.makedirs(user_dir, exist_ok=True)

        # Save photos
        for i, photo in enumerate(photos):
            photo_data = base64.b64decode(photo.split(',')[1])
            with open(os.path.join(user_dir, f'photo_{i+1}.jpg'), 'wb') as f:
                f.write(photo_data)

        return jsonify({'status': 'success', 'message': 'User data saved.'})

    else:
        return '''
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
            </head>
            <body>
                <video id="video" width="640" height="480" autoplay></video>
                <canvas id="canvas" width="640" height="480" style="display:none;"></canvas>
                    <label>Name: <input id="username" type="text"/></label>
                <button id="submitimage">Submit New Data</button>
                <script>
                    const video = document.getElementById('video');
                    const canvas = document.getElementById('canvas');
                    const submit = document.getElementById('submitimage');
                    const usernameInput = document.getElementById('username');
                    let photos = [];
                    let photoCount = 0;

                    async function initCamera() {
                        try {
                            const stream = await navigator.mediaDevices.getUserMedia({ video: true });
                            video.srcObject = stream;
                        } catch (err) {
                            console.error('Error accessing camera:', err);
                        }
                    }

                    function capturePhoto() {
                        const context = canvas.getContext('2d');
                        context.drawImage(video, 0, 0, canvas.width, canvas.height);
                        const imageData = canvas.toDataURL('image/jpeg');
                        photos.push(imageData);
                    }

                    async function submitData() {
                        if (photoCount < 3) {
                            capturePhoto();
                            photoCount++;
                            setTimeout(submitData, 1000); // Capture a photo every second
                        } else {
                            const username = usernameInput.value;
                            const response = await fetch('/new_user', {
                                method: 'POST',
                                body: JSON.stringify({ username, photos }),
                                headers: {
                                    'Content-Type': 'application/json'
                                }
                            });
                            const result = await response.json();
                            console.log(result);
                        }
                    }

                    submit.addEventListener('click', () => {
                        photoCount = 0;
                        photos = [];
                        submitData();
                    });

                    initCamera();
                </script>
            </body>
            </html>
        '''



if __name__ == '__main__':
    app.run(host='0.0.0.0')

https://plmrfpv1u5-496ff2e9c6d22116-5000-colab.googleusercontent.com/
 * Serving Flask app '__main__'
 * Debug mode: off


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.28.0.12:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:32:59] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:00] "GET /favicon.ico HTTP/1.1" 404 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:01] "POST / HTTP/1.1" 200 -


24-06-04 06:33:01 - Searching [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:02] "POST / HTTP/1.1" 200 -


24-06-04 06:33:02 - Searching [[[130 137 140]
  [130 137 140]
  [131 138 141]
  ...
  [136 147 151]
  [133 145 147]
  [129 141 143]]

 [[130 137 140]
  [130 137 140]
  [130 137 140]
  ...
  [137 148 152]
  [134 146 148]
  [130 142 144]]

 [[130 137 140]
  [130 137 140]
  [130 137 140]
  ...
  [136 148 150]
  [131 143 145]
  [126 138 140]]

 ...

 [[193 173  95]
  [192 173 100]
  [195 176 115]
  ...
  [ 20  25  24]
  [ 23  28  27]
  [ 23  28  26]]

 [[192 173  92]
  [189 170  97]
  [194 174 116]
  ...
  [ 23  25  25]
  [ 22  27  26]
  [ 22  27  26]]

 [[193 174  93]
  [189 170  97]
  [194 174 116]
  ...
  [ 26  28  28]
  [ 23  28  27]
  [ 22  27  26]]] in 36 length datastore
24-06-04 06:33:03 - Searching [[[136 148 142]
  [136 148 142]
  [137 148 145]
  ...
  [141 156 158]
  [137 155 156]
  [135 153 154]]

 [[136 148 142]
  [137 149 143]
  [137 148 145]
  ...
  [139 154 156]
  [137 152 154]
  [133 151 152]]

 [[136 147 144]
  [136 147 144]
  [137 148 146]
  ...
  [141 154 156]
  [138 15

INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:03] "POST / HTTP/1.1" 200 -


24-06-04 06:33:03 - find function duration 0.3668506145477295 seconds
24-06-04 06:33:04 - Searching [[[140 147 150]
  [140 147 150]
  [141 148 151]
  ...
  [149 159 153]
  [147 158 150]
  [144 155 147]]

 [[141 148 151]
  [141 148 151]
  [141 148 151]
  ...
  [151 161 155]
  [149 159 153]
  [146 157 149]]

 [[141 148 151]
  [141 148 151]
  [141 148 151]
  ...
  [146 157 154]
  [142 153 150]
  [138 150 144]]

 ...

 [[194 176 113]
  [195 179 120]
  [199 182 131]
  ...
  [ 29  31  39]
  [ 26  28  36]
  [ 23  26  31]]

 [[192 174 113]
  [197 183 125]
  [205 190 141]
  ...
  [ 27  30  34]
  [ 29  30  34]
  [ 30  31  35]]

 [[191 176 114]
  [196 182 124]
  [200 186 137]
  ...
  [ 28  31  35]
  [ 27  29  30]
  [ 28  30  31]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:04] "POST / HTTP/1.1" 200 -


24-06-04 06:33:04 - find function duration 0.35930681228637695 seconds
24-06-04 06:33:05 - Searching [[[145 149 154]
  [142 146 151]
  [141 146 149]
  ...
  [145 157 151]
  [145 156 153]
  [148 159 156]]

 [[144 148 153]
  [142 147 150]
  [141 146 149]
  ...
  [145 157 151]
  [143 154 151]
  [142 153 150]]

 [[142 149 152]
  [140 147 150]
  [140 147 150]
  ...
  [146 157 154]
  [141 152 150]
  [136 147 145]]

 ...

 [[210 191 124]
  [200 182 119]
  [202 185 129]
  ...
  [ 30  32  32]
  [ 26  28  28]
  [ 35  37  37]]

 [[202 183 115]
  [199 182 115]
  [205 191 132]
  ...
  [ 28  28  28]
  [ 26  26  26]
  [ 33  34  32]]

 [[196 178 107]
  [198 182 115]
  [210 197 135]
  ...
  [ 30  28  28]
  [ 29  27  26]
  [ 29  27  26]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:05] "POST / HTTP/1.1" 200 -


24-06-04 06:33:05 - find function duration 0.367387056350708 seconds
24-06-04 06:33:06 - Searching [[[156 166 173]
  [154 164 171]
  [155 164 168]
  ...
  [171 170 174]
  [171 170 172]
  [169 168 170]]

 [[157 167 174]
  [155 165 172]
  [155 164 168]
  ...
  [174 173 177]
  [171 170 172]
  [168 167 169]]

 [[158 167 171]
  [157 166 170]
  [156 165 169]
  ...
  [174 175 179]
  [169 170 174]
  [163 164 168]]

 ...

 [[216 195 144]
  [214 194 146]
  [219 199 158]
  ...
  [ 39  35  46]
  [ 43  37  48]
  [ 43  35  46]]

 [[215 195 147]
  [211 193 146]
  [216 198 157]
  ...
  [ 37  33  39]
  [ 43  34  44]
  [ 44  35  45]]

 [[212 192 144]
  [210 192 145]
  [220 201 163]
  ...
  [ 42  36  41]
  [ 42  34  41]
  [ 42  31  39]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:06] "POST / HTTP/1.1" 200 -


24-06-04 06:33:06 - find function duration 0.40137529373168945 seconds
24-06-04 06:33:07 - Searching [[[167 177 171]
  [166 176 170]
  [166 175 172]
  ...
  [171 183 183]
  [173 183 183]
  [173 183 183]]

 [[165 175 169]
  [166 176 170]
  [166 175 172]
  ...
  [172 184 184]
  [171 181 181]
  [169 179 179]]

 [[165 175 169]
  [167 177 171]
  [168 177 174]
  ...
  [170 182 182]
  [168 177 180]
  [164 173 176]]

 ...

 [[230 204 144]
  [230 206 148]
  [228 206 154]
  ...
  [ 41  41  47]
  [ 38  39  43]
  [ 40  41  45]]

 [[234 207 150]
  [231 206 150]
  [237 214 164]
  ...
  [ 49  47  53]
  [ 44  43  47]
  [ 45  44  46]]

 [[232 205 148]
  [227 202 146]
  [239 216 168]
  ...
  [ 47  45  51]
  [ 43  39  44]
  [ 42  39  41]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:08] "POST / HTTP/1.1" 200 -


24-06-04 06:33:08 - find function duration 0.5083203315734863 seconds


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:08] "POST / HTTP/1.1" 200 -


24-06-04 06:33:08 - Searching [[[177 187 187]
  [177 187 187]
  [176 186 186]
  ...
  [190 196 203]
  [187 193 200]
  [183 189 196]]

 [[176 186 186]
  [176 186 186]
  [176 186 186]
  ...
  [187 193 200]
  [184 190 197]
  [179 185 192]]

 [[177 185 185]
  [177 185 185]
  [177 185 185]
  ...
  [183 191 198]
  [180 186 193]
  [175 181 188]]

 ...

 [[240 223 156]
  [240 223 160]
  [247 232 176]
  ...
  [ 45  47  57]
  [ 47  50  58]
  [ 52  55  63]]

 [[234 216 155]
  [234 218 159]
  [246 229 178]
  ...
  [ 45  48  53]
  [ 52  55  59]
  [ 47  51  52]]

 [[229 211 152]
  [231 214 158]
  [246 229 180]
  ...
  [ 44  46  47]
  [ 46  50  51]
  [ 45  50  49]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:09] "POST / HTTP/1.1" 200 -


24-06-04 06:33:09 - Searching [[[181 189 189]
  [181 189 189]
  [181 188 191]
  ...
  [185 195 202]
  [182 194 200]
  [180 192 198]]

 [[181 189 189]
  [181 189 189]
  [181 188 191]
  ...
  [184 194 201]
  [180 192 198]
  [177 189 195]]

 [[179 189 189]
  [179 189 189]
  [179 188 191]
  ...
  [183 192 201]
  [178 189 197]
  [175 186 194]]

 ...

 [[198 202 190]
  [199 203 191]
  [198 204 193]
  ...
  [ 48  50  61]
  [ 47  49  59]
  [ 51  54  62]]

 [[196 203 188]
  [198 205 192]
  [200 206 195]
  ...
  [ 40  44  55]
  [ 39  45  52]
  [ 44  50  55]]

 [[196 203 188]
  [199 206 191]
  [202 208 197]
  ...
  [ 44  51  60]
  [ 40  48  55]
  [ 38  47  51]]] in 36 length datastore
24-06-04 06:33:10 - Searching [[[176 187 191]
  [176 187 191]
  [176 186 193]
  ...
  [166 178 180]
  [168 177 180]
  [169 178 181]]

 [[177 188 192]
  [176 187 191]
  [175 185 192]
  ...
  [167 179 181]
  [169 178 181]
  [170 179 182]]

 [[178 189 193]
  [176 187 191]
  [174 185 189]
  ...
  [170 179 182]
  [170 17

INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:10] "POST / HTTP/1.1" 200 -


24-06-04 06:33:10 - find function duration 0.3615996837615967 seconds
24-06-04 06:33:11 - Searching [[[196 205 208]
  [195 204 207]
  [192 204 206]
  ...
  [167 183 176]
  [167 184 175]
  [166 183 174]]

 [[198 207 210]
  [197 206 209]
  [193 205 207]
  ...
  [167 183 176]
  [166 183 174]
  [165 182 173]]

 [[196 205 208]
  [195 204 207]
  [192 204 206]
  ...
  [168 182 176]
  [167 182 174]
  [166 181 173]]

 ...

 [[147 154 139]
  [147 155 138]
  [148 155 140]
  ...
  [214 209 194]
  [213 208 193]
  [218 214 196]]

 [[147 156 143]
  [144 154 138]
  [144 153 140]
  ...
  [215 212 197]
  [212 209 194]
  [215 212 197]]

 [[150 159 146]
  [145 154 141]
  [144 153 140]
  ...
  [216 215 201]
  [212 212 196]
  [212 212 196]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:11] "POST / HTTP/1.1" 200 -


24-06-04 06:33:11 - find function duration 0.3687760829925537 seconds


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:12] "POST / HTTP/1.1" 200 -


24-06-04 06:33:12 - Searching [[[207 214 217]
  [207 214 217]
  [206 214 214]
  ...
  [171 192 194]
  [175 193 194]
  [174 192 193]]

 [[207 214 217]
  [207 214 217]
  [206 214 214]
  ...
  [165 186 188]
  [170 190 191]
  [175 193 194]]

 [[204 213 216]
  [204 213 216]
  [204 214 214]
  ...
  [157 178 180]
  [165 184 187]
  [172 191 194]]

 ...

 [[190 197 170]
  [191 198 171]
  [192 198 173]
  ...
  [202 216 222]
  [184 200 206]
  [107 123 129]]

 [[189 196 169]
  [189 196 169]
  [187 196 170]
  ...
  [197 213 220]
  [179 197 204]
  [125 143 150]]

 [[189 196 169]
  [189 196 169]
  [186 195 169]
  ...
  [194 212 219]
  [183 200 209]
  [128 147 155]]] in 36 length datastore
24-06-04 06:33:13 - Searching [[[208 214 213]
  [208 214 213]
  [208 214 213]
  ...
  [151 175 181]
  [151 176 180]
  [147 172 176]]

 [[208 214 213]
  [208 214 213]
  [208 214 213]
  ...
  [148 172 178]
  [148 173 177]
  [148 173 177]]

 [[208 213 214]
  [208 213 214]
  [208 213 214]
  ...
  [141 165 171]
  [142 16

INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:14] "POST / HTTP/1.1" 200 -


24-06-04 06:33:14 - find function duration 0.43941760063171387 seconds
24-06-04 06:33:14 - Searching [[[201 210 214]
  [201 210 214]
  [203 210 213]
  ...
  [171 182 186]
  [174 183 187]
  [174 183 187]]

 [[201 210 214]
  [201 210 214]
  [203 210 213]
  ...
  [171 182 186]
  [174 183 187]
  [175 184 188]]

 [[203 210 213]
  [203 210 213]
  [203 210 213]
  ...
  [171 183 189]
  [174 184 191]
  [174 184 191]]

 ...

 [[164 173 152]
  [165 174 153]
  [167 177 154]
  ...
  [ 88  95  92]
  [ 69  75  70]
  [ 55  61  56]]

 [[165 174 153]
  [166 175 154]
  [167 177 154]
  ...
  [ 96 103 100]
  [ 75  81  76]
  [ 57  63  58]]

 [[165 174 153]
  [166 175 154]
  [167 177 154]
  ...
  [ 98 105 102]
  [ 74  80  75]
  [ 52  58  53]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:14] "POST / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:15] "POST / HTTP/1.1" 200 -


24-06-04 06:33:15 - Searching [[[191 192 196]
  [191 192 196]
  [191 193 194]
  ...
  [172 182 182]
  [173 183 183]
  [174 184 184]]

 [[191 192 196]
  [191 192 196]
  [190 192 193]
  ...
  [172 182 182]
  [173 183 183]
  [173 183 183]]

 [[190 191 195]
  [190 191 195]
  [190 192 193]
  ...
  [172 181 184]
  [173 182 185]
  [173 182 185]]

 ...

 [[153 159 142]
  [153 159 142]
  [152 158 141]
  ...
  [ 30  31  35]
  [ 31  32  36]
  [ 31  32  36]]

 [[154 160 143]
  [153 159 142]
  [153 159 142]
  ...
  [ 37  38  42]
  [ 38  39  43]
  [ 37  38  42]]

 [[154 160 143]
  [153 159 142]
  [153 159 142]
  ...
  [ 36  37  41]
  [ 36  37  41]
  [ 34  35  39]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:16] "POST / HTTP/1.1" 200 -


24-06-04 06:33:16 - Searching [[[193 197 186]
  [191 195 184]
  [188 195 182]
  ...
  [169 183 171]
  [170 184 172]
  [171 185 173]]

 [[192 196 185]
  [191 195 184]
  [188 195 182]
  ...
  [169 183 171]
  [170 184 172]
  [172 186 174]]

 [[192 196 185]
  [191 195 184]
  [188 194 183]
  ...
  [170 184 173]
  [171 185 174]
  [172 186 175]]

 ...

 [[142 151 124]
  [141 150 123]
  [142 149 122]
  ...
  [ 24  25  29]
  [ 24  27  31]
  [ 25  28  32]]

 [[142 151 124]
  [141 150 123]
  [142 148 123]
  ...
  [ 25  26  30]
  [ 24  27  31]
  [ 25  28  32]]

 [[142 151 124]
  [141 150 123]
  [142 148 123]
  ...
  [ 24  25  29]
  [ 23  26  30]
  [ 23  26  30]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:17] "POST / HTTP/1.1" 200 -


24-06-04 06:33:17 - Searching [[[188 194 189]
  [188 194 189]
  [190 194 189]
  ...
  [171 183 177]
  [171 183 177]
  [173 185 179]]

 [[188 194 189]
  [188 194 189]
  [190 194 189]
  ...
  [171 183 177]
  [171 183 177]
  [173 185 179]]

 [[188 194 189]
  [188 194 189]
  [190 194 189]
  ...
  [171 183 177]
  [171 183 177]
  [173 185 179]]

 ...

 [[135 138 116]
  [134 137 115]
  [131 137 112]
  ...
  [ 20  25  28]
  [ 19  24  27]
  [ 19  24  27]]

 [[133 136 114]
  [134 137 115]
  [134 138 113]
  ...
  [ 20  25  28]
  [ 19  24  27]
  [ 18  23  26]]

 [[130 133 111]
  [133 136 114]
  [135 139 114]
  ...
  [ 20  25  28]
  [ 19  24  27]
  [ 18  23  26]]] in 36 length datastore
24-06-04 06:33:18 - Searching [[[187 194 189]
  [187 194 189]
  [187 194 189]
  ...
  [176 184 184]
  [175 183 182]
  [174 182 181]]

 [[187 194 189]
  [187 194 189]
  [187 194 189]
  ...
  [175 183 183]
  [176 184 183]
  [176 184 183]]

 [[188 194 189]
  [188 194 189]
  [188 194 189]
  ...
  [174 182 182]
  [176 18

INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:19] "POST / HTTP/1.1" 200 -


24-06-04 06:33:19 - find function duration 0.4136793613433838 seconds
24-06-04 06:33:19 - Searching [[[188 193 194]
  [185 190 191]
  [181 189 188]
  ...
  [186 196 196]
  [186 197 195]
  [187 198 196]]

 [[184 189 190]
  [184 189 190]
  [181 189 188]
  ...
  [187 197 197]
  [187 198 196]
  [187 198 196]]

 [[184 189 190]
  [185 190 191]
  [184 192 191]
  ...
  [188 198 198]
  [187 198 196]
  [187 198 196]]

 ...

 [[254 254 242]
  [247 247 235]
  [221 223 211]
  ...
  [193 192 172]
  [199 199 181]
  [209 209 191]]

 [[255 255 246]
  [243 242 232]
  [223 224 214]
  ...
  [184 183 162]
  [191 192 172]
  [204 205 185]]

 [[254 252 244]
  [237 235 227]
  [222 223 214]
  ...
  [181 180 159]
  [188 189 169]
  [203 204 184]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:19] "POST / HTTP/1.1" 200 -


24-06-04 06:33:19 - find function duration 0.45789456367492676 seconds
24-06-04 06:33:20 - Searching [[[181 187 192]
  [181 187 192]
  [181 188 191]
  ...
  [187 196 200]
  [188 197 201]
  [188 197 201]]

 [[181 187 192]
  [181 188 191]
  [181 188 191]
  ...
  [187 196 200]
  [188 197 201]
  [188 197 201]]

 [[181 188 191]
  [181 188 191]
  [181 188 191]
  ...
  [189 195 200]
  [190 196 201]
  [190 196 201]]

 ...

 [[255 253 240]
  [255 255 244]
  [255 251 238]
  ...
  [202 200 189]
  [199 198 184]
  [199 198 184]]

 [[255 255 248]
  [255 254 247]
  [255 250 243]
  ...
  [200 200 188]
  [192 192 180]
  [191 191 179]]

 [[255 252 248]
  [255 247 243]
  [252 245 242]
  ...
  [199 199 187]
  [188 188 176]
  [186 186 174]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:21] "POST / HTTP/1.1" 200 -


24-06-04 06:33:21 - find function duration 0.5486679077148438 seconds
24-06-04 06:33:21 - Searching [[[184 189 190]
  [184 189 190]
  [183 188 189]
  ...
  [190 197 200]
  [190 197 200]
  [191 198 201]]

 [[183 188 189]
  [183 188 189]
  [183 188 189]
  ...
  [190 197 200]
  [190 197 200]
  [190 197 200]]

 [[183 188 189]
  [183 188 189]
  [183 189 188]
  ...
  [190 197 200]
  [190 197 200]
  [190 197 200]]

 ...

 [[255 255 238]
  [255 255 240]
  [253 252 232]
  ...
  [206 209 184]
  [202 204 174]
  [206 210 175]]

 [[255 255 242]
  [255 255 242]
  [254 254 238]
  ...
  [203 205 176]
  [190 194 159]
  [192 197 158]]

 [[255 255 245]
  [255 253 242]
  [252 251 237]
  ...
  [187 189 159]
  [169 173 137]
  [177 183 142]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:22] "POST / HTTP/1.1" 200 -


24-06-04 06:33:22 - find function duration 0.35544276237487793 seconds


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:22] "POST / HTTP/1.1" 200 -


24-06-04 06:33:22 - Searching [[[181 187 192]
  [181 187 192]
  [181 187 192]
  ...
  [192 197 198]
  [193 197 198]
  [193 197 198]]

 [[181 187 192]
  [181 187 192]
  [181 187 192]
  ...
  [193 198 199]
  [194 198 199]
  [194 198 199]]

 [[181 187 192]
  [181 187 192]
  [181 187 192]
  ...
  [193 198 199]
  [195 199 200]
  [195 199 200]]

 ...

 [[255 255 239]
  [255 255 240]
  [255 253 235]
  ...
  [201 205 193]
  [199 205 188]
  [201 207 188]]

 [[255 255 243]
  [255 255 242]
  [255 252 237]
  ...
  [197 204 189]
  [192 201 181]
  [191 200 179]]

 [[255 253 242]
  [255 254 243]
  [255 253 239]
  ...
  [197 205 188]
  [183 192 172]
  [175 184 163]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:23] "POST / HTTP/1.1" 200 -


24-06-04 06:33:23 - Searching [[[181 189 188]
  [181 189 188]
  [180 188 187]
  ...
  [194 197 201]
  [195 198 202]
  [195 198 202]]

 [[180 188 187]
  [180 188 187]
  [180 188 187]
  ...
  [194 197 201]
  [194 197 201]
  [195 198 202]]

 [[182 188 187]
  [182 188 187]
  [182 188 187]
  ...
  [194 197 201]
  [194 197 201]
  [194 197 201]]

 ...

 [[255 253 242]
  [255 255 241]
  [255 255 237]
  ...
  [207 204 190]
  [203 198 183]
  [204 200 182]]

 [[255 255 245]
  [255 254 243]
  [253 253 237]
  ...
  [204 203 189]
  [193 190 175]
  [188 185 170]]

 [[253 252 242]
  [254 254 242]
  [252 251 237]
  ...
  [204 203 189]
  [189 186 172]
  [181 178 163]]] in 36 length datastore


INFO:werkzeug:127.0.0.1 - - [04/Jun/2024 06:33:24] "POST / HTTP/1.1" 200 -


24-06-04 06:33:24 - Searching [[[186 190 191]
  [186 190 191]
  [185 189 190]
  ...
  [198 201 205]
  [197 200 204]
  [196 199 203]]

 [[186 190 191]
  [186 190 191]
  [186 190 191]
  ...
  [196 199 203]
  [196 199 203]
  [196 199 203]]

 [[187 191 192]
  [186 190 191]
  [186 190 191]
  ...
  [195 198 202]
  [195 198 202]
  [197 200 204]]

 ...

 [[255 255 238]
  [254 255 235]
  [255 255 239]
  ...
  [204 202 192]
  [199 197 186]
  [203 201 190]]

 [[255 253 242]
  [255 255 241]
  [255 254 243]
  ...
  [202 201 191]
  [190 189 179]
  [193 192 182]]

 [[255 255 247]
  [254 253 243]
  [246 245 235]
  ...
  [203 202 192]
  [183 182 172]
  [185 184 174]]] in 36 length datastore
